/* eslint-disable @typescript-eslint/naming-convention */
import type { IFileConfig } from "./type";

/** 文件图标配置 */
export const fileConfig: IFileConfig = {
  git: {
    iconPath: "./file/git.svg",
    fileNames: [
      ".git",
      ".gitignore",
      ".gitignore-global",
      ".gitignore_global",
      ".gitattributes",
      ".gitattributes-global",
      ".gitattributes_global",
      ".gitconfig",
      ".gitmodules",
      ".gitkeep",
      ".gitinclude",
      ".git-blame-ignore",
      ".git-blame-ignore-revs",
      ".git-for-windows-updater",
      "git-history",
    ],
    fileExtensions: ["patch"],
    languageIds: ["git", "git-commit", "git-rebase", "ignore"],
  },
  yaml: {
    iconPath: "./file/yaml.svg",
    fileNames: [],
    fileExtensions: ["yml", "yaml", "yml.dist", "yaml.dist", "YAML-tmLanguage"],
    languageIds: ["yaml"],
  },
  xml: {
    iconPath: "./file/xml.svg",
    fileNames: [".htaccess"],
    fileExtensions: ["xml", "plist", "xsd", "dtd", "xsl", "xslt", "resx", "iml", "xquery", "tmLanguage", "manifest", "project", "xml.dist", "xml.dist.sample", "dmn", "jrxml"],
    languageIds: ["xml", "xquery", "xsl"],
  },
  matlab: {
    iconPath: "./file/matlab.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: ["matlab"],
  },
  settings: {
    iconPath: "./file/settings.svg",
    fileNames: [".jshintignore", ".buildignore", ".mrconfig", ".yardopts", "manifest.mf", ".clang-format", ".clang-tidy"],
    fileExtensions: ["ini", "dlc", "dll", "config", "conf", "properties", "prop", "settings", "option", "props", "toml", "prefs", "sln.dotsettings", "sln.dotsettings.user", "cfg"],
    languageIds: ["makefile", "toml", "ini", "properties"],
  },
  shaderlab: {
    iconPath: "./file/shaderlab.svg",
    fileNames: [],
    fileExtensions: ["unity"],
    languageIds: ["shaderlab"],
  },
  diff: {
    iconPath: "./file/diff.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: ["diff"],
  },
  json: {
    iconPath: "./file/json.svg",
    fileNames: [".jscsrc", ".jshintrc", "composer.lock", ".jsbeautifyrc", ".esformatter", "cdp.pid", ".lintstagedrc"],
    fileExtensions: ["json", "jsonc", "tsbuildinfo", "json5", "jsonl", "ndjson"],
    languageIds: ["json", "jsonc", "json5"],
  },
  blink: {
    iconPath: "./file/blink.svg",
    fileNames: [],
    fileExtensions: ["blink"],
    languageIds: ["blink"],
  },
  java: {
    iconPath: "./file/java.svg",
    fileNames: [],
    fileExtensions: ["java", "jsp"],
    languageIds: ["java"],
  },
  razor: {
    iconPath: "./file/razor.svg",
    fileNames: [],
    fileExtensions: ["cshtml", "vbhtml"],
    languageIds: ["razor", "aspnetcorerazor"],
  },
  python: {
    iconPath: "./file/python.svg",
    fileNames: [],
    fileExtensions: ["py"],
    languageIds: ["python"],
  },
  javascript: {
    iconPath: "./file/javascript.svg",
    fileNames: [],
    fileExtensions: ["esx", "mjs"],
    languageIds: ["javascript"],
  },
  typescript: {
    iconPath: "./file/typescript.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: ["typescript"],
  },
  scala: {
    iconPath: "./file/scala.svg",
    fileNames: [],
    fileExtensions: ["scala", "sc"],
    languageIds: ["scala"],
  },
  handlebars: {
    iconPath: "./file/handlebars.svg",
    fileNames: [],
    fileExtensions: ["hbs", "mustache"],
    languageIds: ["handlebars"],
  },
  perl: {
    iconPath: "./file/perl.svg",
    fileNames: [],
    fileExtensions: ["pm", "raku"],
    languageIds: ["perl", "perl6"],
  },
  haxe: {
    iconPath: "./file/haxe.svg",
    fileNames: [],
    fileExtensions: ["hx"],
    languageIds: ["haxe", "hxml"],
  },
  puppet: {
    iconPath: "./file/puppet.svg",
    fileNames: [],
    fileExtensions: ["pp"],
    languageIds: ["puppet"],
  },
  elixir: {
    iconPath: "./file/elixir.svg",
    fileNames: [],
    fileExtensions: ["ex", "exs", "eex", "leex", "heex"],
    languageIds: ["elixir"],
  },
  livescript: {
    iconPath: "./file/livescript.svg",
    fileNames: [],
    fileExtensions: ["ls"],
    languageIds: ["livescript"],
  },
  erlang: {
    iconPath: "./file/erlang.svg",
    fileNames: [],
    fileExtensions: ["erl"],
    languageIds: ["erlang"],
  },
  twig: {
    iconPath: "./file/twig.svg",
    fileNames: [],
    fileExtensions: ["twig"],
    languageIds: ["twig"],
  },
  julia: {
    iconPath: "./file/julia.svg",
    fileNames: [],
    fileExtensions: ["jl"],
    languageIds: ["julia"],
  },
  elm: {
    iconPath: "./file/elm.svg",
    fileNames: [],
    fileExtensions: ["elm"],
    languageIds: ["elm"],
  },
  purescript: {
    iconPath: "./file/purescript.svg",
    fileNames: [],
    fileExtensions: ["pure", "purs"],
    languageIds: ["purescript"],
  },
  stylus: {
    iconPath: "./file/stylus.svg",
    fileNames: [],
    fileExtensions: ["styl"],
    languageIds: ["stylus"],
  },
  nunjucks: {
    iconPath: "./file/nunjucks.svg",
    fileNames: [],
    fileExtensions: ["njk", "nunjucks"],
    languageIds: ["nunjucks"],
  },
  pug: {
    iconPath: "./file/pug.svg",
    fileNames: [".pug-lintrc", ".pug-lintrc.js", ".pug-lintrc.json"],
    fileExtensions: ["jade", "pug"],
    languageIds: ["pug", "jade"],
  },
  robot: {
    iconPath: "./file/robot.svg",
    fileNames: [],
    fileExtensions: ["robot"],
    languageIds: ["robotframework"],
  },
  sass: {
    iconPath: "./file/sass.svg",
    fileNames: [],
    fileExtensions: ["scss", "sass"],
    languageIds: ["sass", "scss"],
  },
  less: {
    iconPath: "./file/less.svg",
    fileNames: [],
    fileExtensions: ["less"],
    languageIds: ["less"],
  },
  css: {
    iconPath: "./file/css.svg",
    fileNames: [],
    fileExtensions: ["css"],
    languageIds: ["css"],
  },
  visualstudio: {
    iconPath: "./file/visualstudio.svg",
    fileNames: [],
    fileExtensions: ["csproj", "ruleset", "sln", "suo", "vb", "vbs", "vcxitems", "vcxitems.filters", "vcxproj", "vcxproj.filters"],
    languageIds: ["testOutput", "vb"],
  },
  angular: {
    iconPath: "./file/angular.svg",
    fileNames: ["angular-cli.json", ".angular-cli.json", "angular.json", "ng-package.json"],
    fileExtensions: ["module.ts", "module.js", "ng-template"],
    languageIds: ["ng-template"],
  },
  graphql: {
    iconPath: "./file/graphql.svg",
    fileNames: [
      ".graphqlconfig",
      ".graphqlrc",
      ".graphqlrc.json",
      ".graphqlrc.js",
      ".graphqlrc.cjs",
      ".graphqlrc.ts",
      ".graphqlrc.toml",
      ".graphqlrc.yaml",
      ".graphqlrc.yml",
      "graphql.config.json",
      "graphql.config.js",
      "graphql.config.cjs",
      "graphql.config.ts",
      "graphql.config.toml",
      "graphql.config.yaml",
      "graphql.config.yml",
    ],
    fileExtensions: ["graphql", "gql"],
    languageIds: ["graphql"],
  },
  solidity: {
    iconPath: "./file/solidity.svg",
    fileNames: [],
    fileExtensions: ["sol"],
    languageIds: ["solidity"],
  },
  autoit: {
    iconPath: "./file/autoit.svg",
    fileNames: [],
    fileExtensions: ["au3"],
    languageIds: ["autoit"],
  },
  haml: {
    iconPath: "./file/haml.svg",
    fileNames: [],
    fileExtensions: ["haml"],
    languageIds: ["haml"],
  },
  yang: {
    iconPath: "./file/yang.svg",
    fileNames: [],
    fileExtensions: ["yang"],
    languageIds: ["yang"],
  },
  terraform: {
    iconPath: "./file/terraform.svg",
    fileNames: [],
    fileExtensions: ["tf", "tf.json", "tfvars", "tfstate"],
    languageIds: ["terraform"],
  },
  applescript: {
    iconPath: "./file/applescript.svg",
    fileNames: [],
    fileExtensions: ["applescript", "ipa"],
    languageIds: ["applescript"],
  },
  cake: {
    iconPath: "./file/cake.svg",
    fileNames: [],
    fileExtensions: ["cake"],
    languageIds: ["cake"],
  },
  cucumber: {
    iconPath: "./file/cucumber.svg",
    fileNames: [],
    fileExtensions: ["feature", "features"],
    languageIds: ["cucumber"],
  },
  nim: {
    iconPath: "./file/nim.svg",
    fileNames: [],
    fileExtensions: ["nim", "nimble"],
    languageIds: ["nim", "nimble"],
  },
  apiblueprint: {
    iconPath: "./file/apiblueprint.svg",
    fileNames: [],
    fileExtensions: ["apib", "apiblueprint"],
    languageIds: ["apiblueprint"],
  },
  riot: {
    iconPath: "./file/riot.svg",
    fileNames: [],
    fileExtensions: ["riot", "tag"],
    languageIds: ["riot"],
  },
  postcss: {
    iconPath: "./file/postcss.svg",
    fileNames: [
      "postcss.config.js",
      "postcss.config.cjs",
      "postcss.config.ts",
      "postcss.config.cts",
      ".postcssrc.js",
      ".postcssrc.cjs",
      ".postcssrc.ts",
      ".postcssrc.cts",
      ".postcssrc",
      ".postcssrc.json",
      ".postcssrc.yaml",
      ".postcssrc.yml",
    ],
    fileExtensions: ["pcss", "sss"],
    languageIds: ["postcss"],
  },
  coldfusion: {
    iconPath: "./file/coldfusion.svg",
    fileNames: [],
    fileExtensions: ["cfml", "cfc", "lucee", "cfm"],
    languageIds: ["lang-cfml"],
  },
  haskell: {
    iconPath: "./file/haskell.svg",
    fileNames: [],
    fileExtensions: ["hs"],
    languageIds: ["haskell"],
  },
  dhall: {
    iconPath: "./file/dhall.svg",
    fileNames: [],
    fileExtensions: ["dhall", "dhallb"],
    languageIds: ["dhall"],
  },
  cabal: {
    iconPath: "./file/cabal.svg",
    fileNames: ["cabal.project", "cabal.project.freeze", "cabal.project.local"],
    fileExtensions: ["cabal"],
    languageIds: ["cabal"],
  },
  nix: {
    iconPath: "./file/nix.svg",
    fileNames: [],
    fileExtensions: ["nix"],
    languageIds: ["nix"],
  },
  ruby: {
    iconPath: "./file/ruby.svg",
    fileNames: [],
    fileExtensions: ["rb", "erb"],
    languageIds: ["ruby"],
  },
  slim: {
    iconPath: "./file/slim.svg",
    fileNames: [],
    fileExtensions: ["slim"],
    languageIds: ["slim"],
  },
  php: {
    iconPath: "./file/php.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: ["php"],
  },
  php_elephant: {
    iconPath: "./file/php_elephant.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  php_elephant_pink: {
    iconPath: "./file/php_elephant_pink.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  hack: {
    iconPath: "./file/hack.svg",
    fileNames: [".hhconfig"],
    fileExtensions: [],
    languageIds: ["hack"],
  },
  react: {
    iconPath: "./file/react.svg",
    fileNames: [],
    fileExtensions: ["jsx"],
    languageIds: ["javascriptreact"],
  },
  mjml: {
    iconPath: "./file/mjml.svg",
    fileNames: [".mjmlconfig"],
    fileExtensions: ["mjml"],
    languageIds: ["mjml"],
  },
  processing: {
    iconPath: "./file/processing.svg",
    fileNames: [],
    fileExtensions: ["pde"],
    languageIds: ["processing"],
  },
  hcl: {
    iconPath: "./file/hcl.svg",
    fileNames: [],
    fileExtensions: ["hcl"],
    languageIds: ["hcl"],
  },
  go: {
    iconPath: "./file/go.svg",
    fileNames: [],
    fileExtensions: ["go"],
    languageIds: ["go"],
  },
  go_gopher: {
    iconPath: "./file/go_gopher.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  nodejs_alt: {
    iconPath: "./file/nodejs_alt.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  django: {
    iconPath: "./file/django.svg",
    fileNames: [],
    fileExtensions: ["djt"],
    languageIds: ["django-html", "django-txt"],
  },
  html: {
    iconPath: "./file/html.svg",
    fileNames: [],
    fileExtensions: ["htm", "xhtml", "html_vm", "asp"],
    languageIds: ["html"],
  },
  godot: {
    iconPath: "./file/godot.svg",
    fileNames: [],
    fileExtensions: ["gd"],
    languageIds: ["gdscript"],
  },
  "godot-assets": {
    iconPath: "./file/godot-assets.svg",
    fileNames: [".gdignore", "._sc_", "_sc_"],
    fileExtensions: ["godot", "tres", "tscn", "gdns", "gdnlib", "gdshader", "gdshaderinc", "gdextension"],
    languageIds: ["gdresource", "gdshader"],
  },
  vim: {
    iconPath: "./file/vim.svg",
    fileNames: [],
    fileExtensions: ["vimrc", "gvimrc", "exrc", "vim", "viminfo"],
    languageIds: ["viml"],
  },
  silverstripe: {
    iconPath: "./file/silverstripe.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  prolog: {
    iconPath: "./file/prolog.svg",
    fileNames: [],
    fileExtensions: ["p", "pro", "pl"],
    languageIds: ["prolog"],
  },
  pawn: {
    iconPath: "./file/pawn.svg",
    fileNames: [],
    fileExtensions: ["pwn", "amx"],
    languageIds: ["pawn"],
  },
  reason: {
    iconPath: "./file/reason.svg",
    fileNames: [],
    fileExtensions: ["re", "rei"],
    languageIds: ["reason", "reason_lisp"],
  },
  sml: {
    iconPath: "./file/sml.svg",
    fileNames: [],
    fileExtensions: ["sml", "mlton", "mlb", "sig", "fun", "cm", "lex", "use", "grm"],
    languageIds: ["sml"],
  },
  tex: {
    iconPath: "./file/tex.svg",
    fileNames: [],
    fileExtensions: ["tex", "sty", "dtx", "ltx"],
    languageIds: ["tex", "doctex", "latex", "latex-expl3"],
  },
  salesforce: {
    iconPath: "./file/salesforce.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: ["apex"],
  },
  sas: {
    iconPath: "./file/sas.svg",
    fileNames: [],
    fileExtensions: ["sas", "sas7bdat", "sashdat", "astore", "ast", "sast"],
    languageIds: ["sas"],
  },
  docker: {
    iconPath: "./file/docker.svg",
    fileNames: [
      "dockerfile",
      "dockerfile.prod",
      "dockerfile.production",
      "dockerfile.alpha",
      "dockerfile.beta",
      "dockerfile.stage",
      "dockerfile.staging",
      "dockerfile.dev",
      "dockerfile.development",
      "dockerfile.local",
      "dockerfile.test",
      "dockerfile.testing",
      "dockerfile.ci",
      "dockerfile.web",
      "dockerfile.worker",
      "docker-compose.yml",
      "docker-compose.override.yml",
      "docker-compose.prod.yml",
      "docker-compose.production.yml",
      "docker-compose.alpha.yml",
      "docker-compose.beta.yml",
      "docker-compose.stage.yml",
      "docker-compose.staging.yml",
      "docker-compose.dev.yml",
      "docker-compose.development.yml",
      "docker-compose.local.yml",
      "docker-compose.test.yml",
      "docker-compose.testing.yml",
      "docker-compose.ci.yml",
      "docker-compose.web.yml",
      "docker-compose.worker.yml",
      "docker-compose.yaml",
      "docker-compose.override.yaml",
      "docker-compose.prod.yaml",
      "docker-compose.production.yaml",
      "docker-compose.alpha.yaml",
      "docker-compose.beta.yaml",
      "docker-compose.stage.yaml",
      "docker-compose.staging.yaml",
      "docker-compose.dev.yaml",
      "docker-compose.development.yaml",
      "docker-compose.local.yaml",
      "docker-compose.test.yaml",
      "docker-compose.testing.yaml",
      "docker-compose.ci.yaml",
      "docker-compose.web.yaml",
      "docker-compose.worker.yaml",
      "compose.yaml",
      "compose.override.yaml",
      "compose.prod.yaml",
      "compose.production.yaml",
      "compose.alpha.yaml",
      "compose.beta.yaml",
      "compose.stage.yaml",
      "compose.staging.yaml",
      "compose.dev.yaml",
      "compose.development.yaml",
      "compose.local.yaml",
      "compose.test.yaml",
      "compose.testing.yaml",
      "compose.ci.yaml",
      "compose.web.yaml",
      "compose.worker.yaml",
      "compose.yml",
      "compose.override.yml",
      "compose.prod.yml",
      "compose.production.yml",
      "compose.alpha.yml",
      "compose.beta.yml",
      "compose.stage.yml",
      "compose.staging.yml",
      "compose.dev.yml",
      "compose.development.yml",
      "compose.local.yml",
      "compose.test.yml",
      "compose.testing.yml",
      "compose.ci.yml",
      "compose.web.yml",
      "compose.worker.yml",
    ],
    fileExtensions: ["dockerignore", "dockerfile", "docker-compose.yml", "docker-compose.yaml", "compose.yaml", "compose.yml"],
    languageIds: ["dockerfile"],
  },
  table: {
    iconPath: "./file/table.svg",
    fileNames: [],
    fileExtensions: ["xlsx", "xlsm", "xls", "csv", "tsv", "psv", "ods"],
    languageIds: ["csv", "tsv", "psv"],
  },
  csharp: {
    iconPath: "./file/csharp.svg",
    fileNames: [],
    fileExtensions: ["cs", "csx"],
    languageIds: ["csharp"],
  },
  console: {
    iconPath: "./file/console.svg",
    fileNames: ["commit-msg", "pre-commit", "pre-push", "post-merge"],
    fileExtensions: ["sh", "ksh", "csh", "tcsh", "zsh", "bash", "bat", "cmd", "awk", "fish", "exp", "nu"],
    languageIds: ["bat", "awk", "shellscript"],
  },
  c: {
    iconPath: "./file/c.svg",
    fileNames: [],
    fileExtensions: ["c", "i", "mi"],
    languageIds: ["c"],
  },
  cpp: {
    iconPath: "./file/cpp.svg",
    fileNames: [],
    fileExtensions: ["cc", "cpp", "cxx", "c++", "cp", "mii", "ii"],
    languageIds: ["cpp"],
  },
  "objective-c": {
    iconPath: "./file/objective-c.svg",
    fileNames: [],
    fileExtensions: ["m"],
    languageIds: ["objective-c"],
  },
  "objective-cpp": {
    iconPath: "./file/objective-cpp.svg",
    fileNames: [],
    fileExtensions: ["mm"],
    languageIds: ["objective-cpp"],
  },
  coffee: {
    iconPath: "./file/coffee.svg",
    fileNames: [],
    fileExtensions: ["coffee", "cson", "iced"],
    languageIds: ["coffeescript"],
  },
  fsharp: {
    iconPath: "./file/fsharp.svg",
    fileNames: [],
    fileExtensions: ["fs", "fsx", "fsi", "fsproj"],
    languageIds: ["fsharp"],
  },
  editorconfig: {
    iconPath: "./file/editorconfig.svg",
    fileNames: [".editorconfig"],
    fileExtensions: [],
    languageIds: ["editorconfig"],
  },
  clojure: {
    iconPath: "./file/clojure.svg",
    fileNames: [],
    fileExtensions: ["clj", "cljs", "cljc"],
    languageIds: ["clojure"],
  },
  groovy: {
    iconPath: "./file/groovy.svg",
    fileNames: [],
    fileExtensions: ["groovy"],
    languageIds: ["groovy"],
  },
  markdown: {
    iconPath: "./file/markdown.svg",
    fileNames: [],
    fileExtensions: ["md", "markdown", "rst"],
    languageIds: ["markdown"],
  },
  jinja: {
    iconPath: "./file/jinja.svg",
    fileNames: [],
    fileExtensions: ["jinja", "jinja2", "j2", "jinja-html"],
    languageIds: ["jinja"],
  },
  proto: {
    iconPath: "./file/proto.svg",
    fileNames: [],
    fileExtensions: ["proto"],
    languageIds: ["proto"],
  },
  "python-misc": {
    iconPath: "./file/python-misc.svg",
    fileNames: ["requirements.txt", "pipfile", ".python-version", "manifest.in", "pylintrc", ".pylintrc", "pyproject.toml"],
    fileExtensions: ["pyc", "whl"],
    languageIds: ["pip-requirements"],
  },
  vue: {
    iconPath: "./file/vue.svg",
    fileNames: [],
    fileExtensions: ["vue"],
    languageIds: ["vue", "vue-postcss", "vue-html"],
  },
  lua: {
    iconPath: "./file/lua.svg",
    fileNames: [".luacheckrc"],
    fileExtensions: ["lua"],
    languageIds: ["lua"],
  },
  lib: {
    iconPath: "./file/lib.svg",
    fileNames: [],
    fileExtensions: ["lib", "bib"],
    languageIds: ["bibtex", "bibtex-style"],
  },
  log: {
    iconPath: "./file/log.svg",
    fileNames: [],
    fileExtensions: ["log"],
    languageIds: ["log"],
  },
  jupyter: {
    iconPath: "./file/jupyter.svg",
    fileNames: [],
    fileExtensions: ["ipynb"],
    languageIds: ["jupyter"],
  },
  document: {
    iconPath: "./file/document.svg",
    fileNames: [],
    fileExtensions: ["txt"],
    languageIds: ["plaintext"],
  },
  pdf: {
    iconPath: "./file/pdf.svg",
    fileNames: [],
    fileExtensions: ["pdf"],
    languageIds: ["pdf"],
  },
  powershell: {
    iconPath: "./file/powershell.svg",
    fileNames: [],
    fileExtensions: ["ps1", "psm1", "psd1", "ps1xml", "psc1", "pssc"],
    languageIds: ["powershell"],
  },
  r: {
    iconPath: "./file/r.svg",
    fileNames: [".Rhistory"],
    fileExtensions: ["r", "rmd"],
    languageIds: ["r", "rsweave"],
  },
  rust: {
    iconPath: "./file/rust.svg",
    fileNames: [],
    fileExtensions: ["rs", "ron"],
    languageIds: ["rust"],
  },
  database: {
    iconPath: "./file/database.svg",
    fileNames: [],
    fileExtensions: ["pdb", "sql", "pks", "pkb", "accdb", "mdb", "sqlite", "sqlite3", "pgsql", "postgres", "psql", "db", "db3"],
    languageIds: ["sql"],
  },
  kusto: {
    iconPath: "./file/kusto.svg",
    fileNames: [],
    fileExtensions: ["kql"],
    languageIds: ["kql"],
  },
  lock: {
    iconPath: "./file/lock.svg",
    fileNames: ["security.md", "security.txt", "security"],
    fileExtensions: ["lock"],
    languageIds: ["ssh_config"],
  },
  svg: {
    iconPath: "./file/svg.svg",
    fileNames: [],
    fileExtensions: ["svg"],
    languageIds: ["svg"],
  },
  swift: {
    iconPath: "./file/swift.svg",
    fileNames: [],
    fileExtensions: ["swift"],
    languageIds: ["swift"],
  },
  react_ts: {
    iconPath: "./file/react_ts.svg",
    fileNames: [],
    fileExtensions: ["tsx"],
    languageIds: ["typescriptreact"],
  },
  search: {
    iconPath: "./file/search.svg",
    fileNames: [],
    fileExtensions: ["code-search"],
    languageIds: ["search-result"],
  },
  minecraft: {
    iconPath: "./file/minecraft.svg",
    fileNames: [".mcattributes", ".mcdefinitions", ".mcignore"],
    fileExtensions: ["mcfunction", "mcmeta", "mcr", "mca", "mcgame", "mclevel", "mcworld", "mine", "mus", "mcstructure", "mcpack", "mcaddon", "mctemplate", "mcproject"],
    languageIds: ["mcfunction"],
  },
  rescript: {
    iconPath: "./file/rescript.svg",
    fileNames: [],
    fileExtensions: ["res"],
    languageIds: ["rescript"],
  },
  otne: {
    iconPath: "./file/otne.svg",
    fileNames: [],
    fileExtensions: ["otne"],
    languageIds: ["otne"],
  },
  twine: {
    iconPath: "./file/twine.svg",
    fileNames: [],
    fileExtensions: ["tw", "twee"],
    languageIds: ["twee3", "twee3-harlowe-3", "twee3-chapbook-1", "twee3-sugarcube-2"],
  },
  grain: {
    iconPath: "./file/grain.svg",
    fileNames: [],
    fileExtensions: ["gr"],
    languageIds: ["grain"],
  },
  lolcode: {
    iconPath: "./file/lolcode.svg",
    fileNames: [],
    fileExtensions: ["lol"],
    languageIds: ["lolcode"],
  },
  idris: {
    iconPath: "./file/idris.svg",
    fileNames: [],
    fileExtensions: ["idr", "ibc"],
    languageIds: ["idris"],
  },
  chess: {
    iconPath: "./file/chess.svg",
    fileNames: [],
    fileExtensions: ["pgn", "fen"],
    languageIds: ["pgn"],
  },
  gemini: {
    iconPath: "./file/gemini.svg",
    fileNames: [],
    fileExtensions: ["gmi", "gemini"],
    languageIds: ["gemini", "text-gemini"],
  },
  vlang: {
    iconPath: "./file/vlang.svg",
    fileNames: ["vpkg.json", "v.mod"],
    fileExtensions: ["v"],
    languageIds: ["v"],
  },
  wolframlanguage: {
    iconPath: "./file/wolframlanguage.svg",
    fileNames: [],
    fileExtensions: ["wl", "wls"],
    languageIds: ["wolfram"],
  },
  shader: {
    iconPath: "./file/shader.svg",
    fileNames: [],
    fileExtensions: [
      "glsl",
      "vert",
      "tesc",
      "tese",
      "geom",
      "frag",
      "comp",
      "vert.glsl",
      "tesc.glsl",
      "tese.glsl",
      "geom.glsl",
      "frag.glsl",
      "comp.glsl",
      "vertex.glsl",
      "geometry.glsl",
      "fragment.glsl",
      "compute.glsl",
      "ts.glsl",
      "gs.glsl",
      "vs.glsl",
      "fs.glsl",
      "shader",
      "vertexshader",
      "fragmentshader",
      "geometryshader",
      "computeshader",
      "hlsl",
      "pixel.hlsl",
      "geometry.hlsl",
      "compute.hlsl",
      "tessellation.hlsl",
      "px.hlsl",
      "geom.hlsl",
      "comp.hlsl",
      "tess.hlsl",
      "wgsl",
    ],
    languageIds: ["hlsl", "glsl", "wgsl"],
  },
  tree: {
    iconPath: "./file/tree.svg",
    fileNames: [],
    fileExtensions: ["tree"],
    languageIds: ["tree"],
  },
  svelte: {
    iconPath: "./file/svelte.svg",
    fileNames: ["svelte.config.js", "svelte.config.cjs"],
    fileExtensions: ["svelte"],
    languageIds: ["svelte"],
  },
  dart: {
    iconPath: "./file/dart.svg",
    fileNames: [".pubignore"],
    fileExtensions: ["dart"],
    languageIds: ["dart"],
  },
  cadence: {
    iconPath: "./file/cadence.svg",
    fileNames: [],
    fileExtensions: ["cdc"],
    languageIds: ["cadence"],
  },
  stylable: {
    iconPath: "./file/stylable.svg",
    fileNames: [],
    fileExtensions: ["st.css"],
    languageIds: ["stylable"],
  },
  blink_light: {
    iconPath: "./file/blink_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  jinja_light: {
    iconPath: "./file/jinja_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  playwright: {
    iconPath: "./file/playwright.svg",
    fileNames: ["playwright.config.js", "playwright.config.mjs", "playwright.config.ts", "playwright-ct.config.js", "playwright-ct.config.mjs", "playwright-ct.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  sublime: {
    iconPath: "./file/sublime.svg",
    fileNames: [],
    fileExtensions: ["sublime-project", "sublime-workspace"],
    languageIds: [],
  },
  image: {
    iconPath: "./file/image.svg",
    fileNames: [],
    fileExtensions: [
      "png",
      "jpeg",
      "jpg",
      "gif",
      "ico",
      "tif",
      "tiff",
      "psd",
      "psb",
      "ami",
      "apx",
      "avif",
      "bmp",
      "bpg",
      "brk",
      "cur",
      "dds",
      "dng",
      "exr",
      "fpx",
      "gbr",
      "img",
      "jbig2",
      "jb2",
      "jng",
      "jxr",
      "pgf",
      "pic",
      "raw",
      "webp",
      "eps",
      "afphoto",
      "ase",
      "aseprite",
      "clip",
      "cpt",
      "heif",
      "heic",
      "kra",
      "mdp",
      "ora",
      "pdn",
      "reb",
      "sai",
      "tga",
      "xcf",
      "jfif",
      "ppm",
      "pbm",
      "pgm",
      "pnm",
      "icns",
    ],
    languageIds: [],
  },
  routing: {
    iconPath: "./file/routing.svg",
    fileNames: ["router.js", "router.jsx", "router.ts", "router.tsx", "routes.js", "routes.jsx", "routes.ts", "routes.tsx"],
    fileExtensions: ["routing.ts", "routing.tsx", "routing.js", "routing.jsx", "routes.ts", "routes.tsx", "routes.js", "routes.jsx"],
    languageIds: [],
  },
  "typescript-def": {
    iconPath: "./file/typescript-def.svg",
    fileNames: [],
    fileExtensions: ["d.ts", "d.cts", "d.mts"],
    languageIds: [],
  },
  markojs: {
    iconPath: "./file/markojs.svg",
    fileNames: [],
    fileExtensions: ["marko"],
    languageIds: [],
  },
  astro: {
    iconPath: "./file/astro.svg",
    fileNames: ["astro.config.js", "astro.config.mjs", "astro.config.cjs", "astro.config.ts", "astro.config.cts", "astro.config.mts"],
    fileExtensions: ["astro"],
    languageIds: [],
  },
  vscode: {
    iconPath: "./file/vscode.svg",
    fileNames: [],
    fileExtensions: ["vscodeignore", "vsixmanifest", "vsix", "code-workplace", "code-workspace", "code-profile", "code-snippets"],
    languageIds: [],
  },
  qsharp: {
    iconPath: "./file/qsharp.svg",
    fileNames: [],
    fileExtensions: ["qs"],
    languageIds: [],
  },
  zip: {
    iconPath: "./file/zip.svg",
    fileNames: [],
    fileExtensions: ["zip", "tar", "gz", "xz", "lzma", "lz4", "br", "bz2", "bzip2", "gzip", "brotli", "7z", "rar", "tz", "txz", "tgz"],
    languageIds: [],
  },
  vala: {
    iconPath: "./file/vala.svg",
    fileNames: [],
    fileExtensions: ["vala"],
    languageIds: [],
  },
  zig: {
    iconPath: "./file/zig.svg",
    fileNames: [],
    fileExtensions: ["zig"],
    languageIds: [],
  },
  exe: {
    iconPath: "./file/exe.svg",
    fileNames: [],
    fileExtensions: ["exe", "msi"],
    languageIds: [],
  },
  hex: {
    iconPath: "./file/hex.svg",
    fileNames: [],
    fileExtensions: ["dat", "bin", "hex"],
    languageIds: [],
  },
  jar: {
    iconPath: "./file/jar.svg",
    fileNames: [],
    fileExtensions: ["jar"],
    languageIds: [],
  },
  javaclass: {
    iconPath: "./file/javaclass.svg",
    fileNames: [],
    fileExtensions: ["class"],
    languageIds: [],
  },
  h: {
    iconPath: "./file/h.svg",
    fileNames: [],
    fileExtensions: ["h"],
    languageIds: [],
  },
  hpp: {
    iconPath: "./file/hpp.svg",
    fileNames: [],
    fileExtensions: ["hh", "hpp", "hxx", "h++", "hp", "tcc", "inl"],
    languageIds: [],
  },
  rc: {
    iconPath: "./file/rc.svg",
    fileNames: [],
    fileExtensions: ["rc"],
    languageIds: [],
  },
  "go-mod": {
    iconPath: "./file/go-mod.svg",
    fileNames: ["go.mod", "go.sum", "go.work", "go.work.sum"],
    fileExtensions: [],
    languageIds: [],
  },
  url: {
    iconPath: "./file/url.svg",
    fileNames: [],
    fileExtensions: ["url"],
    languageIds: [],
  },
  gradle: {
    iconPath: "./file/gradle.svg",
    fileNames: ["gradle.properties", "gradlew", "gradle-wrapper.properties"],
    fileExtensions: ["gradle"],
    languageIds: [],
  },
  word: {
    iconPath: "./file/word.svg",
    fileNames: [],
    fileExtensions: ["doc", "docx", "rtf", "odt"],
    languageIds: [],
  },
  certificate: {
    iconPath: "./file/certificate.svg",
    fileNames: [
      "copying",
      "copying.md",
      "copying.rst",
      "copying.txt",
      "copyright",
      "copyright.md",
      "copyright.rst",
      "copyright.txt",
      "license",
      "license-agpl",
      "license-apache",
      "license-bsd",
      "license-mit",
      "license-gpl",
      "license-lgpl",
      "license.md",
      "license.rst",
      "license.txt",
      "licence",
      "licence-agpl",
      "licence-apache",
      "licence-bsd",
      "licence-mit",
      "licence-gpl",
      "licence-lgpl",
      "licence.md",
      "licence.rst",
      "licence.txt",
    ],
    fileExtensions: ["cer", "cert", "crt"],
    languageIds: [],
  },
  key: {
    iconPath: "./file/key.svg",
    fileNames: [".htpasswd"],
    fileExtensions: ["pub", "key", "pem", "asc", "gpg", "passwd"],
    languageIds: [],
  },
  font: {
    iconPath: "./file/font.svg",
    fileNames: [],
    fileExtensions: ["woff", "woff2", "ttf", "eot", "suit", "otf", "bmap", "fnt", "odttf", "ttc", "font", "fonts", "sui", "ntf", "mrf"],
    languageIds: [],
  },
  gemfile: {
    iconPath: "./file/gemfile.svg",
    fileNames: ["gemfile"],
    fileExtensions: [],
    languageIds: [],
  },
  rubocop: {
    iconPath: "./file/rubocop.svg",
    fileNames: [".rubocop.yml", ".rubocop-todo.yml", ".rubocop_todo.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  rubocop_light: {
    iconPath: "./file/rubocop_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  arduino: {
    iconPath: "./file/arduino.svg",
    fileNames: [],
    fileExtensions: ["ino"],
    languageIds: [],
  },
  powerpoint: {
    iconPath: "./file/powerpoint.svg",
    fileNames: [],
    fileExtensions: ["pptx", "ppt", "pptm", "potx", "potm", "ppsx", "ppsm", "pps", "ppam", "ppa", "odp"],
    languageIds: [],
  },
  video: {
    iconPath: "./file/video.svg",
    fileNames: [],
    fileExtensions: ["webm", "mkv", "flv", "vob", "ogv", "ogg", "gifv", "avi", "mov", "qt", "wmv", "yuv", "rm", "rmvb", "mp4", "m4v", "mpg", "mp2", "mpeg", "mpe", "mpv", "m2v"],
    languageIds: [],
  },
  virtual: {
    iconPath: "./file/virtual.svg",
    fileNames: [],
    fileExtensions: ["vdi", "vbox", "vbox-prev"],
    languageIds: [],
  },
  email: {
    iconPath: "./file/email.svg",
    fileNames: [".mailmap"],
    fileExtensions: ["ics"],
    languageIds: [],
  },
  audio: {
    iconPath: "./file/audio.svg",
    fileNames: [],
    fileExtensions: ["mp3", "flac", "m4a", "wma", "aiff", "wav"],
    languageIds: [],
  },
  raml: {
    iconPath: "./file/raml.svg",
    fileNames: [],
    fileExtensions: ["raml"],
    languageIds: [],
  },
  xaml: {
    iconPath: "./file/xaml.svg",
    fileNames: [],
    fileExtensions: ["xaml"],
    languageIds: [],
  },
  kotlin: {
    iconPath: "./file/kotlin.svg",
    fileNames: [],
    fileExtensions: ["kt", "kts"],
    languageIds: [],
  },
  dart_generated: {
    iconPath: "./file/dart_generated.svg",
    fileNames: [],
    fileExtensions: ["freezed.dart", "g.dart"],
    languageIds: [],
  },
  actionscript: {
    iconPath: "./file/actionscript.svg",
    fileNames: [],
    fileExtensions: ["as"],
    languageIds: [],
  },
  mxml: {
    iconPath: "./file/mxml.svg",
    fileNames: [],
    fileExtensions: ["mxml"],
    languageIds: [],
  },
  autohotkey: {
    iconPath: "./file/autohotkey.svg",
    fileNames: [],
    fileExtensions: ["ahk"],
    languageIds: [],
  },
  flash: {
    iconPath: "./file/flash.svg",
    fileNames: [],
    fileExtensions: ["swf"],
    languageIds: [],
  },
  swc: {
    iconPath: "./file/swc.svg",
    fileNames: [],
    fileExtensions: ["swc"],
    languageIds: [],
  },
  cmake: {
    iconPath: "./file/cmake.svg",
    fileNames: ["cmakelists.txt", "cmakecache.txt"],
    fileExtensions: ["cmake"],
    languageIds: [],
  },
  assembly: {
    iconPath: "./file/assembly.svg",
    fileNames: [],
    fileExtensions: ["asm", "a51", "inc", "nasm", "s", "ms", "agc", "ags", "aea", "argus", "mitigus", "binsource"],
    languageIds: [],
  },
  "vue-config": {
    iconPath: "./file/vue-config.svg",
    fileNames: ["vue.config.js", "vue.config.ts", "vetur.config.js", "vetur.config.ts", "volar.config.js"],
    fileExtensions: [],
    languageIds: [],
  },
  nuxt: {
    iconPath: "./file/nuxt.svg",
    fileNames: ["nuxt.config.js", "nuxt.config.ts", ".nuxtignore"],
    fileExtensions: [],
    languageIds: [],
  },
  ocaml: {
    iconPath: "./file/ocaml.svg",
    fileNames: [],
    fileExtensions: ["ml", "mli", "cmx"],
    languageIds: [],
  },
  odin: {
    iconPath: "./file/odin.svg",
    fileNames: [],
    fileExtensions: ["odin"],
    languageIds: [],
  },
  "javascript-map": {
    iconPath: "./file/javascript-map.svg",
    fileNames: [],
    fileExtensions: ["js.map", "mjs.map", "cjs.map"],
    languageIds: [],
  },
  "css-map": {
    iconPath: "./file/css-map.svg",
    fileNames: [],
    fileExtensions: ["css.map"],
    languageIds: [],
  },
  "test-ts": {
    iconPath: "./file/test-ts.svg",
    fileNames: [],
    fileExtensions: ["spec.ts", "spec.cts", "spec.mts", "cy.ts", "e2e-spec.ts", "e2e-spec.cts", "e2e-spec.mts", "test.ts", "test.cts", "test.mts", "ts.snap", "spec-d.ts", "test-d.ts"],
    languageIds: [],
  },
  "test-jsx": {
    iconPath: "./file/test-jsx.svg",
    fileNames: [],
    fileExtensions: ["spec.tsx", "test.tsx", "tsx.snap", "spec.jsx", "test.jsx", "jsx.snap", "cy.jsx", "cy.tsx", "spec-d.tsx", "test-d.tsx"],
    languageIds: [],
  },
  "test-js": {
    iconPath: "./file/test-js.svg",
    fileNames: [],
    fileExtensions: ["spec.js", "spec.cjs", "spec.mjs", "e2e-spec.js", "e2e-spec.cjs", "e2e-spec.mjs", "test.js", "test.cjs", "test.mjs", "js.snap", "cy.js"],
    languageIds: [],
  },
  "angular-component": {
    iconPath: "./file/angular-component.svg",
    fileNames: [],
    fileExtensions: ["component.ts", "component.js"],
    languageIds: [],
  },
  "angular-guard": {
    iconPath: "./file/angular-guard.svg",
    fileNames: [],
    fileExtensions: ["guard.ts", "guard.js"],
    languageIds: [],
  },
  "angular-service": {
    iconPath: "./file/angular-service.svg",
    fileNames: [],
    fileExtensions: ["service.ts", "service.js"],
    languageIds: [],
  },
  "angular-pipe": {
    iconPath: "./file/angular-pipe.svg",
    fileNames: [],
    fileExtensions: ["pipe.ts", "pipe.js", "filter.js"],
    languageIds: [],
  },
  "angular-directive": {
    iconPath: "./file/angular-directive.svg",
    fileNames: [],
    fileExtensions: ["directive.ts", "directive.js"],
    languageIds: [],
  },
  "angular-resolver": {
    iconPath: "./file/angular-resolver.svg",
    fileNames: [],
    fileExtensions: ["resolver.ts", "resolver.js"],
    languageIds: [],
  },
  smarty: {
    iconPath: "./file/smarty.svg",
    fileNames: [],
    fileExtensions: ["tpl"],
    languageIds: [],
  },
  bucklescript: {
    iconPath: "./file/bucklescript.svg",
    fileNames: [],
    fileExtensions: ["cmj"],
    languageIds: [],
  },
  merlin: {
    iconPath: "./file/merlin.svg",
    fileNames: [],
    fileExtensions: ["merlin"],
    languageIds: [],
  },
  verilog: {
    iconPath: "./file/verilog.svg",
    fileNames: [],
    fileExtensions: ["vhd", "sv", "svh"],
    languageIds: [],
  },
  mathematica: {
    iconPath: "./file/mathematica.svg",
    fileNames: [],
    fileExtensions: ["nb"],
    languageIds: [],
  },
  vercel: {
    iconPath: "./file/vercel.svg",
    fileNames: ["vercel.json", ".vercelignore", "now.json", ".nowignore"],
    fileExtensions: [],
    languageIds: [],
  },
  vercel_light: {
    iconPath: "./file/vercel_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  verdaccio: {
    iconPath: "./file/verdaccio.svg",
    fileNames: ["verdaccio.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  next: {
    iconPath: "./file/next.svg",
    fileNames: ["next.config.js", "next.config.mjs", "next.config.ts", "next.config.mts"],
    fileExtensions: [],
    languageIds: [],
  },
  next_light: {
    iconPath: "./file/next_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  remix: {
    iconPath: "./file/remix.svg",
    fileNames: ["remix.config.js", "remix.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  remix_light: {
    iconPath: "./file/remix_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  laravel: {
    iconPath: "./file/laravel.svg",
    fileNames: ["artisan"],
    fileExtensions: ["blade.php", "inky.php"],
    languageIds: [],
  },
  vfl: {
    iconPath: "./file/vfl.svg",
    fileNames: [".vfl"],
    fileExtensions: ["vfl"],
    languageIds: [],
  },
  kl: {
    iconPath: "./file/kl.svg",
    fileNames: [".kl"],
    fileExtensions: ["kl"],
    languageIds: [],
  },
  posthtml: {
    iconPath: "./file/posthtml.svg",
    fileNames: ["posthtml.config.js", ".posthtmlrc.js", ".posthtmlrc", ".posthtmlrc.json", ".posthtmlrc.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  todo: {
    iconPath: "./file/todo.svg",
    fileNames: ["todo.md", "todos.md"],
    fileExtensions: ["todo"],
    languageIds: [],
  },
  http: {
    iconPath: "./file/http.svg",
    fileNames: ["CNAME"],
    fileExtensions: ["http", "rest"],
    languageIds: [],
  },
  restql: {
    iconPath: "./file/restql.svg",
    fileNames: [],
    fileExtensions: ["rql", "restql"],
    languageIds: [],
  },
  kivy: {
    iconPath: "./file/kivy.svg",
    fileNames: [],
    fileExtensions: ["kv"],
    languageIds: [],
  },
  graphcool: {
    iconPath: "./file/graphcool.svg",
    fileNames: ["project.graphcool"],
    fileExtensions: ["graphcool"],
    languageIds: [],
  },
  sbt: {
    iconPath: "./file/sbt.svg",
    fileNames: [],
    fileExtensions: ["sbt"],
    languageIds: [],
  },
  webpack: {
    iconPath: "./file/webpack.svg",
    fileNames: [
      "webpack.js",
      "webpack.cjs",
      "webpack.mjs",
      "webpack.ts",
      "webpack.cts",
      "webpack.mts",
      "webpack.base.js",
      "webpack.base.cjs",
      "webpack.base.mjs",
      "webpack.base.ts",
      "webpack.base.cts",
      "webpack.base.mts",
      "webpack.config.js",
      "webpack.config.cjs",
      "webpack.config.mjs",
      "webpack.config.ts",
      "webpack.config.cts",
      "webpack.config.mts",
      "webpack.common.js",
      "webpack.common.cjs",
      "webpack.common.mjs",
      "webpack.common.ts",
      "webpack.common.cts",
      "webpack.common.mts",
      "webpack.config.common.js",
      "webpack.config.common.cjs",
      "webpack.config.common.mjs",
      "webpack.config.common.ts",
      "webpack.config.common.cts",
      "webpack.config.common.mts",
      "webpack.config.common.babel.js",
      "webpack.config.common.babel.ts",
      "webpack.dev.js",
      "webpack.dev.cjs",
      "webpack.dev.mjs",
      "webpack.dev.ts",
      "webpack.dev.cts",
      "webpack.dev.mts",
      "webpack.development.js",
      "webpack.development.cjs",
      "webpack.development.mjs",
      "webpack.development.ts",
      "webpack.development.cts",
      "webpack.development.mts",
      "webpack.config.dev.js",
      "webpack.config.dev.cjs",
      "webpack.config.dev.mjs",
      "webpack.config.dev.ts",
      "webpack.config.dev.cts",
      "webpack.config.dev.mts",
      "webpack.config.dev.babel.js",
      "webpack.config.dev.babel.ts",
      "webpack.mix.js",
      "webpack.mix.cjs",
      "webpack.mix.mjs",
      "webpack.mix.ts",
      "webpack.mix.cts",
      "webpack.mix.mts",
      "webpack.prod.js",
      "webpack.prod.cjs",
      "webpack.prod.mjs",
      "webpack.prod.ts",
      "webpack.prod.cts",
      "webpack.prod.mts",
      "webpack.prod.config.js",
      "webpack.prod.config.cjs",
      "webpack.prod.config.mjs",
      "webpack.prod.config.ts",
      "webpack.prod.config.cts",
      "webpack.prod.config.mts",
      "webpack.production.js",
      "webpack.production.cjs",
      "webpack.production.mjs",
      "webpack.production.ts",
      "webpack.production.cts",
      "webpack.production.mts",
      "webpack.server.js",
      "webpack.server.cjs",
      "webpack.server.mjs",
      "webpack.server.ts",
      "webpack.server.cts",
      "webpack.server.mts",
      "webpack.client.js",
      "webpack.client.cjs",
      "webpack.client.mjs",
      "webpack.client.ts",
      "webpack.client.cts",
      "webpack.client.mts",
      "webpack.config.server.js",
      "webpack.config.server.cjs",
      "webpack.config.server.mjs",
      "webpack.config.server.ts",
      "webpack.config.server.cts",
      "webpack.config.server.mts",
      "webpack.config.client.js",
      "webpack.config.client.cjs",
      "webpack.config.client.mjs",
      "webpack.config.client.ts",
      "webpack.config.client.cts",
      "webpack.config.client.mts",
      "webpack.config.production.babel.js",
      "webpack.config.production.babel.ts",
      "webpack.config.prod.babel.js",
      "webpack.config.prod.babel.cjs",
      "webpack.config.prod.babel.mjs",
      "webpack.config.prod.babel.ts",
      "webpack.config.prod.babel.cts",
      "webpack.config.prod.babel.mts",
      "webpack.config.prod.js",
      "webpack.config.prod.cjs",
      "webpack.config.prod.mjs",
      "webpack.config.prod.ts",
      "webpack.config.prod.cts",
      "webpack.config.prod.mts",
      "webpack.config.production.js",
      "webpack.config.production.cjs",
      "webpack.config.production.mjs",
      "webpack.config.production.ts",
      "webpack.config.production.cts",
      "webpack.config.production.mts",
      "webpack.config.staging.js",
      "webpack.config.staging.cjs",
      "webpack.config.staging.mjs",
      "webpack.config.staging.ts",
      "webpack.config.staging.cts",
      "webpack.config.staging.mts",
      "webpack.config.babel.js",
      "webpack.config.babel.ts",
      "webpack.config.base.babel.js",
      "webpack.config.base.babel.ts",
      "webpack.config.base.js",
      "webpack.config.base.cjs",
      "webpack.config.base.mjs",
      "webpack.config.base.ts",
      "webpack.config.base.cts",
      "webpack.config.base.mts",
      "webpack.config.staging.babel.js",
      "webpack.config.staging.babel.ts",
      "webpack.config.coffee",
      "webpack.config.test.js",
      "webpack.config.test.cjs",
      "webpack.config.test.mjs",
      "webpack.config.test.ts",
      "webpack.config.test.cts",
      "webpack.config.test.mts",
      "webpack.config.vendor.js",
      "webpack.config.vendor.cjs",
      "webpack.config.vendor.mjs",
      "webpack.config.vendor.ts",
      "webpack.config.vendor.cts",
      "webpack.config.vendor.mts",
      "webpack.config.vendor.production.js",
      "webpack.config.vendor.production.cjs",
      "webpack.config.vendor.production.mjs",
      "webpack.config.vendor.production.ts",
      "webpack.config.vendor.production.cts",
      "webpack.config.vendor.production.mts",
      "webpack.test.js",
      "webpack.test.cjs",
      "webpack.test.mjs",
      "webpack.test.ts",
      "webpack.test.cts",
      "webpack.test.mts",
      "webpack.dist.js",
      "webpack.dist.cjs",
      "webpack.dist.mjs",
      "webpack.dist.ts",
      "webpack.dist.cts",
      "webpack.dist.mts",
      "webpackfile.js",
      "webpackfile.cjs",
      "webpackfile.mjs",
      "webpackfile.ts",
      "webpackfile.cts",
      "webpackfile.mts",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  ionic: {
    iconPath: "./file/ionic.svg",
    fileNames: ["ionic.config.json", ".io-config.json"],
    fileExtensions: [],
    languageIds: [],
  },
  gulp: {
    iconPath: "./file/gulp.svg",
    fileNames: ["gulpfile.js", "gulpfile.mjs", "gulpfile.ts", "gulpfile.cts", "gulpfile.mts", "gulpfile.babel.js"],
    fileExtensions: [],
    languageIds: [],
  },
  nodejs: {
    iconPath: "./file/nodejs.svg",
    fileNames: ["package.json", "package-lock.json", ".nvmrc", ".esmrc", ".node-version"],
    fileExtensions: [],
    languageIds: [],
  },
  npm: {
    iconPath: "./file/npm.svg",
    fileNames: [".npmignore", ".npmrc"],
    fileExtensions: [],
    languageIds: [],
  },
  yarn: {
    iconPath: "./file/yarn.svg",
    fileNames: [".yarnrc", "yarn.lock", ".yarnclean", ".yarn-integrity", "yarn-error.log", ".yarnrc.yml", ".yarnrc.yaml"],
    fileExtensions: [],
    languageIds: [],
  },
  android: {
    iconPath: "./file/android.svg",
    fileNames: ["androidmanifest.xml"],
    fileExtensions: ["apk", "smali", "dex"],
    languageIds: [],
  },
  tune: {
    iconPath: "./file/tune.svg",
    fileNames: [
      ".env.defaults",
      ".env.example",
      ".env.sample",
      ".env.template",
      ".env.schema",
      ".env.local",
      ".env.dev",
      ".env.development",
      ".env.alpha",
      ".env.e2e",
      ".env.qa",
      ".env.dist",
      ".env.prod",
      ".env.production",
      ".env.stage",
      ".env.staging",
      ".env.preview",
      ".env.test",
      ".env.testing",
      ".env.development.local",
      ".env.qa.local",
      ".env.production.local",
      ".env.staging.local",
      ".env.test.local",
      ".env.uat",
    ],
    fileExtensions: ["env"],
    languageIds: [],
  },
  turborepo: {
    iconPath: "./file/turborepo.svg",
    fileNames: ["turbo.json"],
    fileExtensions: [],
    languageIds: [],
  },
  turborepo_light: {
    iconPath: "./file/turborepo_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  babel: {
    iconPath: "./file/babel.svg",
    fileNames: [
      ".babelrc",
      ".babelrc.cjs",
      ".babelrc.js",
      ".babelrc.mjs",
      ".babelrc.json",
      "babel.config.cjs",
      "babel.config.js",
      "babel.config.mjs",
      "babel.config.json",
      "babel-transform.js",
      ".babel-plugin-macrosrc",
      ".babel-plugin-macrosrc.json",
      ".babel-plugin-macrosrc.yaml",
      ".babel-plugin-macrosrc.yml",
      ".babel-plugin-macrosrc.js",
      "babel-plugin-macros.config.js",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  blitz: {
    iconPath: "./file/blitz.svg",
    fileNames: ["blitz.config.js", "blitz.config.ts", ".blitz.config.compiled.js"],
    fileExtensions: [],
    languageIds: [],
  },
  contributing: {
    iconPath: "./file/contributing.svg",
    fileNames: ["contributing.md", "contributing.rst", "contributing.txt", "contributing"],
    fileExtensions: [],
    languageIds: [],
  },
  readme: {
    iconPath: "./file/readme.svg",
    fileNames: ["readme.md", "readme.rst", "readme.txt", "readme"],
    fileExtensions: [],
    languageIds: [],
  },
  changelog: {
    iconPath: "./file/changelog.svg",
    fileNames: ["changelog", "changelog.md", "changelog.rst", "changelog.txt", "changes", "changes.md", "changes.rst", "changes.txt"],
    fileExtensions: [],
    languageIds: [],
  },
  architecture: {
    iconPath: "./file/architecture.svg",
    fileNames: ["architecture.md", "architecture.rst", "architecture.txt", "architecture"],
    fileExtensions: [],
    languageIds: [],
  },
  credits: {
    iconPath: "./file/credits.svg",
    fileNames: ["credits.md", "credits.rst", "credits.txt", "credits"],
    fileExtensions: [],
    languageIds: [],
  },
  authors: {
    iconPath: "./file/authors.svg",
    fileNames: ["authors.md", "authors.rst", "authors.txt", "authors", "contributors.md", "contributors.rst", "contributors.txt", "contributors"],
    fileExtensions: [],
    languageIds: [],
  },
  flow: {
    iconPath: "./file/flow.svg",
    fileNames: [".flowconfig"],
    fileExtensions: [],
    languageIds: [],
  },
  favicon: {
    iconPath: "./file/favicon.svg",
    fileNames: ["favicon.ico"],
    fileExtensions: [],
    languageIds: [],
  },
  karma: {
    iconPath: "./file/karma.svg",
    fileNames: ["karma.conf.js", "karma.conf.ts", "karma.conf.coffee", "karma.config.js", "karma.config.ts", "karma-main.js", "karma-main.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  bithound: {
    iconPath: "./file/bithound.svg",
    fileNames: [".bithoundrc"],
    fileExtensions: [],
    languageIds: [],
  },
  svgo: {
    iconPath: "./file/svgo.svg",
    fileNames: ["svgo.config.js", "svgo.config.cjs", "svgo.config.mjs"],
    fileExtensions: [],
    languageIds: [],
  },
  appveyor: {
    iconPath: "./file/appveyor.svg",
    fileNames: [".appveyor.yml", "appveyor.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  travis: {
    iconPath: "./file/travis.svg",
    fileNames: [".travis.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  codecov: {
    iconPath: "./file/codecov.svg",
    fileNames: [".codecov.yml", "codecov.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  sonarcloud: {
    iconPath: "./file/sonarcloud.svg",
    fileNames: ["sonar-project.properties", ".sonarcloud.properties", "sonarcloud.yaml"],
    fileExtensions: [],
    languageIds: [],
  },
  protractor: {
    iconPath: "./file/protractor.svg",
    fileNames: ["protractor.conf.js", "protractor.conf.ts", "protractor.conf.coffee", "protractor.config.js", "protractor.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  fusebox: {
    iconPath: "./file/fusebox.svg",
    fileNames: ["fuse.js"],
    fileExtensions: [],
    languageIds: [],
  },
  heroku: {
    iconPath: "./file/heroku.svg",
    fileNames: ["procfile", "procfile.windows"],
    fileExtensions: [],
    languageIds: [],
  },
  gitlab: {
    iconPath: "./file/gitlab.svg",
    fileNames: [],
    fileExtensions: ["gitlab-ci.yml"],
    languageIds: [],
  },
  bower: {
    iconPath: "./file/bower.svg",
    fileNames: [".bowerrc", "bower.json"],
    fileExtensions: [],
    languageIds: [],
  },
  eslint: {
    iconPath: "./file/eslint.svg",
    fileNames: [
      ".eslintrc.js",
      ".eslintrc.cjs",
      ".eslintrc.yaml",
      ".eslintrc.yml",
      ".eslintrc.json",
      ".eslintrc-md.js",
      ".eslintrc-jsdoc.js",
      ".eslintrc",
      ".eslintignore",
      ".eslintcache",
      "eslint.config.js",
      "eslint.config.mjs",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  conduct: {
    iconPath: "./file/conduct.svg",
    fileNames: ["code_of_conduct.md", "code_of_conduct.txt", "code_of_conduct"],
    fileExtensions: [],
    languageIds: [],
  },
  watchman: {
    iconPath: "./file/watchman.svg",
    fileNames: [".watchmanconfig"],
    fileExtensions: [],
    languageIds: [],
  },
  aurelia: {
    iconPath: "./file/aurelia.svg",
    fileNames: ["aurelia.json"],
    fileExtensions: [],
    languageIds: [],
  },
  auto: {
    iconPath: "./file/auto.svg",
    fileNames: [".autorc", "auto.config.js", "auto.config.ts", "auto-config.json", "auto-config.yaml", "auto-config.yml", "auto-config.ts", "auto-config.js"],
    fileExtensions: [],
    languageIds: [],
  },
  auto_light: {
    iconPath: "./file/auto_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  mocha: {
    iconPath: "./file/mocha.svg",
    fileNames: ["mocha.opts", ".mocharc.yml", ".mocharc.yaml", ".mocharc.js", ".mocharc.json", ".mocharc.jsonc"],
    fileExtensions: [],
    languageIds: [],
  },
  jenkins: {
    iconPath: "./file/jenkins.svg",
    fileNames: ["jenkinsfile"],
    fileExtensions: ["jenkinsfile", "jenkins"],
    languageIds: [],
  },
  firebase: {
    iconPath: "./file/firebase.svg",
    fileNames: ["firebase.json", ".firebaserc", "firestore.rules", "firestore.indexes.json"],
    fileExtensions: [],
    languageIds: [],
  },
  figma: {
    iconPath: "./file/figma.svg",
    fileNames: [],
    fileExtensions: ["fig"],
    languageIds: [],
  },
  rollup: {
    iconPath: "./file/rollup.svg",
    fileNames: [
      "rollup.config.js",
      "rollup.config.mjs",
      "rollup.config.ts",
      "rollup-config.js",
      "rollup-config.mjs",
      "rollup-config.ts",
      "rollup.config.common.js",
      "rollup.config.common.mjs",
      "rollup.config.common.ts",
      "rollup.config.base.js",
      "rollup.config.base.mjs",
      "rollup.config.base.ts",
      "rollup.config.prod.js",
      "rollup.config.prod.mjs",
      "rollup.config.prod.ts",
      "rollup.config.dev.js",
      "rollup.config.dev.mjs",
      "rollup.config.dev.ts",
      "rollup.config.prod.vendor.js",
      "rollup.config.prod.vendor.mjs",
      "rollup.config.prod.vendor.ts",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  hardhat: {
    iconPath: "./file/hardhat.svg",
    fileNames: ["hardhat.config.js", "hardhat.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  stylelint: {
    iconPath: "./file/stylelint.svg",
    fileNames: [
      ".stylelintrc",
      "stylelint.config.js",
      "stylelint.config.cjs",
      ".stylelintrc.json",
      ".stylelintrc.yaml",
      ".stylelintrc.yml",
      ".stylelintrc.js",
      ".stylelintrc.cjs",
      ".stylelintignore",
      ".stylelintcache",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  stylelint_light: {
    iconPath: "./file/stylelint_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  "code-climate": {
    iconPath: "./file/code-climate.svg",
    fileNames: [".codeclimate.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  "code-climate_light": {
    iconPath: "./file/code-climate_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  prettier: {
    iconPath: "./file/prettier.svg",
    fileNames: [
      ".prettierrc",
      "prettier.config.js",
      "prettier.config.cjs",
      ".prettierrc.js",
      ".prettierrc.cjs",
      ".prettierrc.json",
      ".prettierrc.json5",
      ".prettierrc.yaml",
      ".prettierrc.yml",
      ".prettierignore",
      ".prettierrc.toml",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  renovate: {
    iconPath: "./file/renovate.svg",
    fileNames: [".renovaterc", ".renovaterc.json", "renovate-config.json", "renovate.json", "renovate.json5"],
    fileExtensions: [],
    languageIds: [],
  },
  apollo: {
    iconPath: "./file/apollo.svg",
    fileNames: ["apollo.config.js"],
    fileExtensions: [],
    languageIds: [],
  },
  nodemon: {
    iconPath: "./file/nodemon.svg",
    fileNames: ["nodemon.json", "nodemon-debug.json"],
    fileExtensions: [],
    languageIds: [],
  },
  webhint: {
    iconPath: "./file/webhint.svg",
    fileNames: [".hintrc"],
    fileExtensions: [],
    languageIds: [],
  },
  browserlist: {
    iconPath: "./file/browserlist.svg",
    fileNames: ["browserslist", ".browserslistrc"],
    fileExtensions: [],
    languageIds: [],
  },
  browserlist_light: {
    iconPath: "./file/browserlist_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  crystal: {
    iconPath: "./file/crystal.svg",
    fileNames: [],
    fileExtensions: ["cr", "ecr"],
    languageIds: [],
  },
  crystal_light: {
    iconPath: "./file/crystal_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  snyk: {
    iconPath: "./file/snyk.svg",
    fileNames: [".snyk"],
    fileExtensions: [],
    languageIds: [],
  },
  drone: {
    iconPath: "./file/drone.svg",
    fileNames: [".drone.yml"],
    fileExtensions: ["drone.yml"],
    languageIds: [],
  },
  drone_light: {
    iconPath: "./file/drone_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  cuda: {
    iconPath: "./file/cuda.svg",
    fileNames: [],
    fileExtensions: ["cu", "cuh"],
    languageIds: [],
  },
  dotjs: {
    iconPath: "./file/dotjs.svg",
    fileNames: [],
    fileExtensions: ["def", "dot", "jst"],
    languageIds: [],
  },
  ejs: {
    iconPath: "./file/ejs.svg",
    fileNames: [],
    fileExtensions: ["ejs"],
    languageIds: [],
  },
  sequelize: {
    iconPath: "./file/sequelize.svg",
    fileNames: [".sequelizerc"],
    fileExtensions: [],
    languageIds: [],
  },
  gatsby: {
    iconPath: "./file/gatsby.svg",
    fileNames: [
      "gatsby-config.js",
      "gatsby-config.mjs",
      "gatsby-config.ts",
      "gatsby-node.js",
      "gatsby-node.mjs",
      "gatsby-node.ts",
      "gatsby-browser.js",
      "gatsby-browser.tsx",
      "gatsby-ssr.js",
      "gatsby-ssr.tsx",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  wakatime: {
    iconPath: "./file/wakatime.svg",
    fileNames: [".wakatime-project"],
    fileExtensions: [".wakatime-project"],
    languageIds: [],
  },
  wakatime_light: {
    iconPath: "./file/wakatime_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  circleci: {
    iconPath: "./file/circleci.svg",
    fileNames: ["circle.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  circleci_light: {
    iconPath: "./file/circleci_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  cloudfoundry: {
    iconPath: "./file/cloudfoundry.svg",
    fileNames: [".cfignore"],
    fileExtensions: [],
    languageIds: [],
  },
  grunt: {
    iconPath: "./file/grunt.svg",
    fileNames: ["gruntfile.js", "gruntfile.ts", "gruntfile.coffee", "gruntfile.babel.js", "gruntfile.babel.ts", "gruntfile.babel.coffee"],
    fileExtensions: [],
    languageIds: [],
  },
  jest: {
    iconPath: "./file/jest.svg",
    fileNames: [
      "jest.config.js",
      "jest.config.cjs",
      "jest.config.mjs",
      "jest.config.ts",
      "jest.config.cts",
      "jest.config.mts",
      "jest.config.json",
      "jest.e2e.config.js",
      "jest.e2e.config.cjs",
      "jest.e2e.config.mjs",
      "jest.e2e.config.ts",
      "jest.e2e.config.cts",
      "jest.e2e.config.mts",
      "jest.e2e.config.json",
      "jest.e2e.json",
      "jest-unit.config.js",
      "jest-e2e.config.js",
      "jest-e2e.config.cjs",
      "jest-e2e.config.mjs",
      "jest-e2e.config.ts",
      "jest-e2e.config.cts",
      "jest-e2e.config.mts",
      "jest-e2e.config.json",
      "jest-e2e.json",
      "jest-github-actions-reporter.js",
      "jest.setup.js",
      "jest.setup.ts",
      "jest.json",
      ".jestrc",
      ".jestrc.js",
      ".jestrc.json",
      "jest.teardown.js",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  storybook: {
    iconPath: "./file/storybook.svg",
    fileNames: [],
    fileExtensions: ["stories.js", "stories.jsx", "stories.mdx", "story.js", "story.jsx", "stories.ts", "stories.tsx", "story.ts", "story.tsx", "stories.svelte", "story.mdx"],
    languageIds: [],
  },
  wepy: {
    iconPath: "./file/wepy.svg",
    fileNames: [],
    fileExtensions: ["wpy"],
    languageIds: [],
  },
  fastlane: {
    iconPath: "./file/fastlane.svg",
    fileNames: ["fastfile", "appfile"],
    fileExtensions: [],
    languageIds: [],
  },
  hcl_light: {
    iconPath: "./file/hcl_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  helm: {
    iconPath: "./file/helm.svg",
    fileNames: [".helmignore"],
    fileExtensions: [],
    languageIds: [],
  },
  san: {
    iconPath: "./file/san.svg",
    fileNames: [],
    fileExtensions: ["san"],
    languageIds: [],
  },
  wallaby: {
    iconPath: "./file/wallaby.svg",
    fileNames: ["wallaby.js", "wallaby.conf.js"],
    fileExtensions: [],
    languageIds: [],
  },
  stencil: {
    iconPath: "./file/stencil.svg",
    fileNames: ["stencil.config.js", "stencil.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  red: {
    iconPath: "./file/red.svg",
    fileNames: [],
    fileExtensions: ["red"],
    languageIds: [],
  },
  makefile: {
    iconPath: "./file/makefile.svg",
    fileNames: ["makefile", "gnumakefile", "kbuild"],
    fileExtensions: ["mk"],
    languageIds: [],
  },
  foxpro: {
    iconPath: "./file/foxpro.svg",
    fileNames: [],
    fileExtensions: ["fxp", "prg"],
    languageIds: [],
  },
  i18n: {
    iconPath: "./file/i18n.svg",
    fileNames: [],
    fileExtensions: ["pot", "po", "mo", "lang"],
    languageIds: [],
  },
  webassembly: {
    iconPath: "./file/webassembly.svg",
    fileNames: [],
    fileExtensions: ["wat", "wasm"],
    languageIds: [],
  },
  "semantic-release": {
    iconPath: "./file/semantic-release.svg",
    fileNames: [".releaserc", ".releaserc.yaml", ".releaserc.yml", ".releaserc.json", ".releaserc.js", "release.config.js"],
    fileExtensions: [],
    languageIds: [],
  },
  "semantic-release_light": {
    iconPath: "./file/semantic-release_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  bitbucket: {
    iconPath: "./file/bitbucket.svg",
    fileNames: ["bitbucket-pipelines.yaml", "bitbucket-pipelines.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  d: {
    iconPath: "./file/d.svg",
    fileNames: [],
    fileExtensions: ["d"],
    languageIds: [],
  },
  mdx: {
    iconPath: "./file/mdx.svg",
    fileNames: [],
    fileExtensions: ["mdx"],
    languageIds: [],
  },
  mdsvex: {
    iconPath: "./file/mdsvex.svg",
    fileNames: [],
    fileExtensions: ["svx"],
    languageIds: [],
  },
  ballerina: {
    iconPath: "./file/ballerina.svg",
    fileNames: [],
    fileExtensions: ["bal", "balx"],
    languageIds: [],
  },
  racket: {
    iconPath: "./file/racket.svg",
    fileNames: [],
    fileExtensions: ["rkt"],
    languageIds: [],
  },
  bazel: {
    iconPath: "./file/bazel.svg",
    fileNames: [".bazelignore", ".bazelrc", ".bazelversion"],
    fileExtensions: ["bzl", "bazel"],
    languageIds: [],
  },
  mint: {
    iconPath: "./file/mint.svg",
    fileNames: [],
    fileExtensions: ["mint"],
    languageIds: [],
  },
  velocity: {
    iconPath: "./file/velocity.svg",
    fileNames: [],
    fileExtensions: ["vm", "fhtml", "vtl"],
    languageIds: [],
  },
  "azure-pipelines": {
    iconPath: "./file/azure-pipelines.svg",
    fileNames: ["azure-pipelines.yml", "azure-pipelines.yaml"],
    fileExtensions: ["azure-pipelines.yml", "azure-pipelines.yaml"],
    languageIds: [],
  },
  azure: {
    iconPath: "./file/azure.svg",
    fileNames: [],
    fileExtensions: ["azcli"],
    languageIds: [],
  },
  vagrant: {
    iconPath: "./file/vagrant.svg",
    fileNames: ["vagrantfile"],
    fileExtensions: ["vagrantfile"],
    languageIds: [],
  },
  prisma: {
    iconPath: "./file/prisma.svg",
    fileNames: ["prisma.yml"],
    fileExtensions: ["prisma"],
    languageIds: [],
  },
  abc: {
    iconPath: "./file/abc.svg",
    fileNames: [],
    fileExtensions: ["abc"],
    languageIds: [],
  },
  asciidoc: {
    iconPath: "./file/asciidoc.svg",
    fileNames: [],
    fileExtensions: ["ad", "adoc", "asciidoc"],
    languageIds: [],
  },
  istanbul: {
    iconPath: "./file/istanbul.svg",
    fileNames: [".nycrc", ".nycrc.json"],
    fileExtensions: [],
    languageIds: [],
  },
  edge: {
    iconPath: "./file/edge.svg",
    fileNames: [],
    fileExtensions: ["edge"],
    languageIds: [],
  },
  scheme: {
    iconPath: "./file/scheme.svg",
    fileNames: [],
    fileExtensions: ["ss", "scm"],
    languageIds: [],
  },
  lisp: {
    iconPath: "./file/lisp.svg",
    fileNames: [],
    fileExtensions: ["lisp", "lsp", "cl", "fast"],
    languageIds: [],
  },
  tailwindcss: {
    iconPath: "./file/tailwindcss.svg",
    fileNames: ["tailwind.js", "tailwind.ts", "tailwind.config.js", "tailwind.config.cjs", "tailwind.config.ts", "tailwind.config.cts"],
    fileExtensions: [],
    languageIds: [],
  },
  "3d": {
    iconPath: "./file/3d.svg",
    fileNames: [],
    fileExtensions: ["stl", "stp", "obj", "ac", "blend", "fbx", "mesh", "mqo", "pmd", "pmx", "skp", "vac", "vdp", "vox"],
    languageIds: [],
  },
  buildkite: {
    iconPath: "./file/buildkite.svg",
    fileNames: ["buildkite.yml", "buildkite.yaml"],
    fileExtensions: [],
    languageIds: [],
  },
  netlify: {
    iconPath: "./file/netlify.svg",
    fileNames: ["netlify.json", "netlify.yml", "netlify.yaml", "netlify.toml"],
    fileExtensions: [],
    languageIds: [],
  },
  netlify_light: {
    iconPath: "./file/netlify_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  nest: {
    iconPath: "./file/nest.svg",
    fileNames: ["nest-cli.json", ".nest-cli.json", "nestconfig.json", ".nestconfig.json"],
    fileExtensions: [],
    languageIds: [],
  },
  moonscript: {
    iconPath: "./file/moonscript.svg",
    fileNames: [],
    fileExtensions: ["moon"],
    languageIds: [],
  },
  percy: {
    iconPath: "./file/percy.svg",
    fileNames: [".percy.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  gitpod: {
    iconPath: "./file/gitpod.svg",
    fileNames: [".gitpod.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  advpl_prw: {
    iconPath: "./file/advpl_prw.svg",
    fileNames: [],
    fileExtensions: ["prw", "prx"],
    languageIds: [],
  },
  advpl_ptm: {
    iconPath: "./file/advpl_ptm.svg",
    fileNames: [],
    fileExtensions: ["ptm"],
    languageIds: [],
  },
  advpl_tlpp: {
    iconPath: "./file/advpl_tlpp.svg",
    fileNames: [],
    fileExtensions: ["tlpp"],
    languageIds: [],
  },
  advpl_include: {
    iconPath: "./file/advpl_include.svg",
    fileNames: [],
    fileExtensions: ["ch"],
    languageIds: [],
  },
  codeowners: {
    iconPath: "./file/codeowners.svg",
    fileNames: ["codeowners"],
    fileExtensions: [],
    languageIds: [],
  },
  gcp: {
    iconPath: "./file/gcp.svg",
    fileNames: [".gcloudignore"],
    fileExtensions: [],
    languageIds: [],
  },
  disc: {
    iconPath: "./file/disc.svg",
    fileNames: [],
    fileExtensions: ["iso"],
    languageIds: [],
  },
  fortran: {
    iconPath: "./file/fortran.svg",
    fileNames: [],
    fileExtensions: ["f", "f77", "f90", "f95", "f03", "f08"],
    languageIds: [],
  },
  tcl: {
    iconPath: "./file/tcl.svg",
    fileNames: [],
    fileExtensions: ["tcl"],
    languageIds: [],
  },
  liquid: {
    iconPath: "./file/liquid.svg",
    fileNames: [],
    fileExtensions: ["liquid"],
    languageIds: [],
  },
  husky: {
    iconPath: "./file/husky.svg",
    fileNames: [".huskyrc", "husky.config.js", ".huskyrc.json", ".huskyrc.js", ".huskyrc.yaml", ".huskyrc.yml"],
    fileExtensions: [],
    languageIds: [],
  },
  coconut: {
    iconPath: "./file/coconut.svg",
    fileNames: [],
    fileExtensions: ["coco"],
    languageIds: [],
  },
  tilt: {
    iconPath: "./file/tilt.svg",
    fileNames: ["tiltfile"],
    fileExtensions: [],
    languageIds: [],
  },
  capacitor: {
    iconPath: "./file/capacitor.svg",
    fileNames: ["capacitor.config.json", "capacitor.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  sketch: {
    iconPath: "./file/sketch.svg",
    fileNames: [],
    fileExtensions: ["sketch"],
    languageIds: [],
  },
  adonis: {
    iconPath: "./file/adonis.svg",
    fileNames: [".adonisrc.json", "ace"],
    fileExtensions: [],
    languageIds: [],
  },
  forth: {
    iconPath: "./file/forth.svg",
    fileNames: [],
    fileExtensions: ["4th", "fth", "frt"],
    languageIds: [],
  },
  uml: {
    iconPath: "./file/uml.svg",
    fileNames: [],
    fileExtensions: ["iuml", "pu", "puml", "plantuml", "wsd"],
    languageIds: [],
  },
  uml_light: {
    iconPath: "./file/uml_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  meson: {
    iconPath: "./file/meson.svg",
    fileNames: ["meson.build", "meson_options.txt"],
    fileExtensions: ["wrap"],
    languageIds: [],
  },
  commitlint: {
    iconPath: "./file/commitlint.svg",
    fileNames: [
      ".commitlintrc",
      ".commitlintrc.js",
      ".commitlintrc.cjs",
      ".commitlintrc.ts",
      ".commitlintrc.cts",
      ".commitlintrc.json",
      ".commitlintrc.yaml",
      ".commitlintrc.yml",
      ".commitlint.yaml",
      ".commitlint.yml",
      "commitlint.config.js",
      "commitlint.config.cjs",
      "commitlint.config.ts",
      "commitlint.config.cts",
    ],
    fileExtensions: [],
    languageIds: [],
  },
  buck: {
    iconPath: "./file/buck.svg",
    fileNames: [".buckconfig"],
    fileExtensions: [],
    languageIds: [],
  },
  nrwl: {
    iconPath: "./file/nrwl.svg",
    fileNames: ["nx.json", ".nxignore"],
    fileExtensions: [],
    languageIds: [],
  },
  opam: {
    iconPath: "./file/opam.svg",
    fileNames: [],
    fileExtensions: ["opam"],
    languageIds: [],
  },
  dune: {
    iconPath: "./file/dune.svg",
    fileNames: ["dune", "dune-project", "dune-workspace", "dune-workspace.dev"],
    fileExtensions: [],
    languageIds: [],
  },
  imba: {
    iconPath: "./file/imba.svg",
    fileNames: [],
    fileExtensions: ["imba"],
    languageIds: [],
  },
  drawio: {
    iconPath: "./file/drawio.svg",
    fileNames: [],
    fileExtensions: ["drawio", "dio"],
    languageIds: [],
  },
  pascal: {
    iconPath: "./file/pascal.svg",
    fileNames: [],
    fileExtensions: ["pas"],
    languageIds: [],
  },
  roadmap: {
    iconPath: "./file/roadmap.svg",
    fileNames: ["roadmap.md", "roadmap.txt", "timeline.md", "timeline.txt", "milestones.md", "milestones.txt"],
    fileExtensions: [],
    languageIds: [],
  },
  nuget: {
    iconPath: "./file/nuget.svg",
    fileNames: ["nuget.config", ".nuspec", "nuget.exe"],
    fileExtensions: ["nupkg"],
    languageIds: [],
  },
  command: {
    iconPath: "./file/command.svg",
    fileNames: [],
    fileExtensions: ["command"],
    languageIds: [],
  },
  stryker: {
    iconPath: "./file/stryker.svg",
    fileNames: ["stryker.conf.json", "stryker.conf.js", "stryker.conf.cjs", "stryker.conf.mjs", ".stryker.conf.json", ".stryker.conf.js", ".stryker.conf.cjs", ".stryker.conf.mjs"],
    fileExtensions: [],
    languageIds: [],
  },
  denizenscript: {
    iconPath: "./file/denizenscript.svg",
    fileNames: [],
    fileExtensions: ["dsc"],
    languageIds: [],
  },
  modernizr: {
    iconPath: "./file/modernizr.svg",
    fileNames: [".modernizrrc", ".modernizrrc.js", ".modernizrrc.json"],
    fileExtensions: [],
    languageIds: [],
  },
  slug: {
    iconPath: "./file/slug.svg",
    fileNames: [".slugignore"],
    fileExtensions: [],
    languageIds: [],
  },
  stitches: {
    iconPath: "./file/stitches.svg",
    fileNames: ["stitches.config.js", "stitches.config.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  stitches_light: {
    iconPath: "./file/stitches_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  nginx: {
    iconPath: "./file/nginx.svg",
    fileNames: ["nginx.conf"],
    fileExtensions: ["nginx", "nginxconfig"],
    languageIds: [],
  },
  replit: {
    iconPath: "./file/replit.svg",
    fileNames: [".replit"],
    fileExtensions: [],
    languageIds: [],
  },
  "rescript-interface": {
    iconPath: "./file/rescript-interface.svg",
    fileNames: [],
    fileExtensions: ["resi"],
    languageIds: [],
  },
  snowpack: {
    iconPath: "./file/snowpack.svg",
    fileNames: ["snowpack.config.js", "snowpack.config.cjs", "snowpack.config.mjs", "snowpack.config.ts", "snowpack.config.cts", "snowpack.config.mts", "snowpack.deps.json", "snowpack.config.json"],
    fileExtensions: [],
    languageIds: [],
  },
  snowpack_light: {
    iconPath: "./file/snowpack_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  brainfuck: {
    iconPath: "./file/brainfuck.svg",
    fileNames: [],
    fileExtensions: ["b", "bf"],
    languageIds: [],
  },
  bicep: {
    iconPath: "./file/bicep.svg",
    fileNames: [],
    fileExtensions: ["bicep"],
    languageIds: [],
  },
  cobol: {
    iconPath: "./file/cobol.svg",
    fileNames: [],
    fileExtensions: ["cob", "cbl"],
    languageIds: [],
  },
  quasar: {
    iconPath: "./file/quasar.svg",
    fileNames: ["quasar.conf.js", "quasar.config.js"],
    fileExtensions: [],
    languageIds: [],
  },
  dependabot: {
    iconPath: "./file/dependabot.svg",
    fileNames: ["dependabot.yml", "dependabot.yaml"],
    fileExtensions: [],
    languageIds: [],
  },
  pipeline: {
    iconPath: "./file/pipeline.svg",
    fileNames: [],
    fileExtensions: ["pipeline"],
    languageIds: [],
  },
  vite: {
    iconPath: "./file/vite.svg",
    fileNames: ["vite.config.js", "vite.config.mjs", "vite.config.cjs", "vite.config.ts", "vite.config.cts", "vite.config.mts"],
    fileExtensions: [],
    languageIds: [],
  },
  vitest: {
    iconPath: "./file/vitest.svg",
    fileNames: ["vitest.config.ts", "vitest.config.mts", "vitest.config.cts", "vitest.config.js", "vitest.config.mjs", "vitest.config.cjs"],
    fileExtensions: [],
    languageIds: [],
  },
  opa: {
    iconPath: "./file/opa.svg",
    fileNames: [],
    fileExtensions: ["rego"],
    languageIds: [],
  },
  lerna: {
    iconPath: "./file/lerna.svg",
    fileNames: ["lerna.json"],
    fileExtensions: [],
    languageIds: [],
  },
  windicss: {
    iconPath: "./file/windicss.svg",
    fileNames: ["windi.config.js", "windi.config.cjs", "windi.config.ts", "windi.config.cts", "windi.config.json"],
    fileExtensions: ["windi"],
    languageIds: [],
  },
  textlint: {
    iconPath: "./file/textlint.svg",
    fileNames: [".textlintrc"],
    fileExtensions: [],
    languageIds: [],
  },
  lilypond: {
    iconPath: "./file/lilypond.svg",
    fileNames: [],
    fileExtensions: ["ly"],
    languageIds: [],
  },
  chess_light: {
    iconPath: "./file/chess_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  sentry: {
    iconPath: "./file/sentry.svg",
    fileNames: [".sentryclirc"],
    fileExtensions: [],
    languageIds: [],
  },
  phpunit: {
    iconPath: "./file/phpunit.svg",
    fileNames: [".phpunit.result.cache", ".phpunit-watcher.yml", "phpunit.xml", "phpunit.xml.dist", "phpunit-watcher.yml", "phpunit-watcher.yml.dist"],
    fileExtensions: [],
    languageIds: [],
  },
  "php-cs-fixer": {
    iconPath: "./file/php-cs-fixer.svg",
    fileNames: [".php_cs", ".php_cs.dist", ".php_cs.php", ".php_cs.dist.php", ".php-cs-fixer.php", ".php-cs-fixer.dist.php"],
    fileExtensions: [],
    languageIds: [],
  },
  robots: {
    iconPath: "./file/robots.svg",
    fileNames: ["robots.txt"],
    fileExtensions: [],
    languageIds: [],
  },
  tsconfig: {
    iconPath: "./file/tsconfig.svg",
    fileNames: [
      "tsconfig.json",
      "tsconfig.app.json",
      "tsconfig.editor.json",
      "tsconfig.spec.json",
      "tsconfig.base.json",
      "tsconfig.build.json",
      "tsconfig.eslint.json",
      "tsconfig.lib.json",
      "tsconfig.lib.prod.json",
      "tsconfig.node.json",
      "tsconfig.test.json",
      "tsconfig.e2e.json",
      "tsconfig.web.json",
      "tsconfig.webworker.json",
      "tsconfig.worker.json",
      "tsconfig.config.json",
      "tsconfig.vitest.json",
      "tsconfig.cjs.json",
      "tsconfig.esm.json",
      "tsconfig.mjs.json",
      "tsconfig.doc.json",
    ],
    fileExtensions: ["tsconfig.json"],
    languageIds: [],
  },
  tauri: {
    iconPath: "./file/tauri.svg",
    fileNames: ["tauri.conf.json", "tauri.config.json", "tauri.linux.conf.json", "tauri.windows.conf.json", "tauri.macos.conf.json"],
    fileExtensions: ["tauri"],
    languageIds: [],
  },
  jsconfig: {
    iconPath: "./file/jsconfig.svg",
    fileNames: ["jsconfig.json"],
    fileExtensions: ["jsconfig.json"],
    languageIds: [],
  },
  maven: {
    iconPath: "./file/maven.svg",
    fileNames: ["maven.config", "jvm.config", "pom.xml"],
    fileExtensions: [],
    languageIds: [],
  },
  ada: {
    iconPath: "./file/ada.svg",
    fileNames: [],
    fileExtensions: ["ada", "adb", "ads", "ali"],
    languageIds: [],
  },
  serverless: {
    iconPath: "./file/serverless.svg",
    fileNames: ["serverless.yml", "serverless.yaml", "serverless.json", "serverless.js", "serverless.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  supabase: {
    iconPath: "./file/supabase.svg",
    fileNames: ["supabase.js", "supabase.py"],
    fileExtensions: [],
    languageIds: [],
  },
  ember: {
    iconPath: "./file/ember.svg",
    fileNames: [".ember-cli", ".ember-cli.js", "ember-cli-builds.js"],
    fileExtensions: [],
    languageIds: [],
  },
  horusec: {
    iconPath: "./file/horusec.svg",
    fileNames: ["horusec-config.json"],
    fileExtensions: ["horusec-config.json"],
    languageIds: [],
  },
  poetry: {
    iconPath: "./file/poetry.svg",
    fileNames: ["poetry.lock"],
    fileExtensions: [],
    languageIds: [],
  },
  coala: {
    iconPath: "./file/coala.svg",
    fileNames: [],
    fileExtensions: ["coarc", "coafile"],
    languageIds: [],
  },
  parcel: {
    iconPath: "./file/parcel.svg",
    fileNames: [".parcelrc"],
    fileExtensions: [],
    languageIds: [],
  },
  dinophp: {
    iconPath: "./file/dinophp.svg",
    fileNames: [],
    fileExtensions: ["bubble", "html.bubble", "php.bubble"],
    languageIds: [],
  },
  teal: {
    iconPath: "./file/teal.svg",
    fileNames: [],
    fileExtensions: ["tl"],
    languageIds: [],
  },
  template: {
    iconPath: "./file/template.svg",
    fileNames: [],
    fileExtensions: ["template"],
    languageIds: [],
  },
  astyle: {
    iconPath: "./file/astyle.svg",
    fileNames: [".astylerc"],
    fileExtensions: [],
    languageIds: [],
  },
  lighthouse: {
    iconPath: "./file/lighthouse.svg",
    fileNames: [".lighthouserc.js", "lighthouserc.js", ".lighthouserc.json", "lighthouserc.json", ".lighthouserc.yml", "lighthouserc.yml", ".lighthouserc.yaml", "lighthouserc.yaml"],
    fileExtensions: [],
    languageIds: [],
  },
  svgr: {
    iconPath: "./file/svgr.svg",
    fileNames: [".svgrrc", "svgr.config.js", ".svgrrc.js", ".svgrrc.yaml", ".svgrrc.yml", ".svgrrc.json"],
    fileExtensions: [],
    languageIds: [],
  },
  rome: {
    iconPath: "./file/rome.svg",
    fileNames: ["rome.json"],
    fileExtensions: [],
    languageIds: [],
  },
  cypress: {
    iconPath: "./file/cypress.svg",
    fileNames: ["cypress.json", "cypress.env.json", "cypress.config.ts", "cypress.config.js", "cypress.config.cjs", "cypress.config.mjs"],
    fileExtensions: [],
    languageIds: [],
  },
  siyuan: {
    iconPath: "./file/siyuan.svg",
    fileNames: [],
    fileExtensions: ["sy"],
    languageIds: [],
  },
  ndst: {
    iconPath: "./file/ndst.svg",
    fileNames: [],
    fileExtensions: ["ndst.yml", "ndst.yaml", "ndst.json"],
    languageIds: [],
  },
  plop: {
    iconPath: "./file/plop.svg",
    fileNames: ["plopfile.js", "plopfile.cjs", "plopfile.mjs", "plopfile.ts"],
    fileExtensions: [],
    languageIds: [],
  },
  tobi: {
    iconPath: "./file/tobi.svg",
    fileNames: [],
    fileExtensions: ["tobi"],
    languageIds: [],
  },
  tobimake: {
    iconPath: "./file/tobimake.svg",
    fileNames: [".tobimake"],
    fileExtensions: [],
    languageIds: [],
  },
  gleam: {
    iconPath: "./file/gleam.svg",
    fileNames: ["gleam.toml"],
    fileExtensions: ["gleam"],
    languageIds: [],
  },
  pnpm: {
    iconPath: "./file/pnpm.svg",
    fileNames: ["pnpm-lock.yaml", "pnpm-workspace.yaml", ".pnpmfile.cjs"],
    fileExtensions: [],
    languageIds: [],
  },
  pnpm_light: {
    iconPath: "./file/pnpm_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  gridsome: {
    iconPath: "./file/gridsome.svg",
    fileNames: ["gridsome.config.js", "gridsome.server.js"],
    fileExtensions: [],
    languageIds: [],
  },
  steadybit: {
    iconPath: "./file/steadybit.svg",
    fileNames: [".steadybit.yml", "steadybit.yml", ".steadybit.yaml", "steadybit.yaml"],
    fileExtensions: ["steadybit.yml", "steadybit.yaml"],
    languageIds: [],
  },
  caddy: {
    iconPath: "./file/caddy.svg",
    fileNames: ["Caddyfile"],
    fileExtensions: [],
    languageIds: [],
  },
  bun: {
    iconPath: "./file/bun.svg",
    fileNames: ["bun.lockb"],
    fileExtensions: [],
    languageIds: [],
  },
  bun_light: {
    iconPath: "./file/bun_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  antlr: {
    iconPath: "./file/antlr.svg",
    fileNames: [],
    fileExtensions: ["g4"],
    languageIds: [],
  },
  pinejs: {
    iconPath: "./file/pinejs.svg",
    fileNames: [],
    fileExtensions: ["pine"],
    languageIds: [],
  },
  "nano-staged": {
    iconPath: "./file/nano-staged.svg",
    fileNames: [".nano-staged.js", "nano-staged.js", ".nano-staged.cjs", "nano-staged.cjs", ".nano-staged.mjs", "nano-staged.mjs", ".nano-staged.json", "nano-staged.json", ".nanostagedrc"],
    fileExtensions: [],
    languageIds: [],
  },
  "nano-staged_light": {
    iconPath: "./file/nano-staged_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  craco: {
    iconPath: "./file/craco.svg",
    fileNames: ["craco.config.ts", "craco.config.js", "craco.config.cjs", ".cracorc.ts", ".cracorc.js", ".cracorc"],
    fileExtensions: [],
    languageIds: [],
  },
  gamemaker: {
    iconPath: "./file/gamemaker.svg",
    fileNames: [],
    fileExtensions: ["gml", "yy", "yyp", "yyz"],
    languageIds: [],
  },
  tldraw: {
    iconPath: "./file/tldraw.svg",
    fileNames: [],
    fileExtensions: ["tldr"],
    languageIds: [],
  },
  tldraw_light: {
    iconPath: "./file/tldraw_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  mercurial: {
    iconPath: "./file/mercurial.svg",
    fileNames: [".hg", ".hgignore", ".hgflow", ".hgrc", "hgrc", "mercurial.ini"],
    fileExtensions: [],
    languageIds: [],
  },
  deno: {
    iconPath: "./file/deno.svg",
    fileNames: ["deno.json", "deno.jsonc", "deno.lock"],
    fileExtensions: [],
    languageIds: [],
  },
  deno_light: {
    iconPath: "./file/deno_light.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  plastic: {
    iconPath: "./file/plastic.svg",
    fileNames: ["plastic.branchexplorer", "plastic.selector", "plastic.wktree", "plastic.workspace", "plastic.workspaces"],
    fileExtensions: [],
    languageIds: [],
  },
  typst: {
    iconPath: "./file/typst.svg",
    fileNames: [],
    fileExtensions: ["typ"],
    languageIds: [],
  },
  file: {
    iconPath: "./file/file.svg",
    fileNames: [],
    fileExtensions: [],
    languageIds: [],
  },
  wxml: {
    iconPath: "./file/wxml.svg",
    fileNames: [],
    fileExtensions: ["wxml"],
    languageIds: [],
  },
  wxss: {
    iconPath: "./file/wxss.svg",
    fileNames: [],
    fileExtensions: ["wxss"],
    languageIds: [],
  },
};
