/* eslint-disable @typescript-eslint/naming-convention */
import type { IFolderConfigData } from "./type";

/** 文件夹📂图标配置 */
export const folderConfig: IFolderConfigData = {
  "folder-src": {
    iconPath: "./folder/src.svg",
    folderNames: ["src", "srcs", "source", "sources", "code"],
    folderNamesExpanded: [],
  },
  "folder-src-open": {
    iconPath: "./folder/src-open.svg",
    folderNames: [],
    folderNamesExpanded: ["src", "srcs", "source", "sources", "code"],
  },
  "folder-dist": {
    iconPath: "./folder/dist.svg",
    folderNames: ["dist", "out", "build", "release", "bin"],
    folderNamesExpanded: [],
  },
  "folder-dist-open": {
    iconPath: "./folder/dist-open.svg",
    folderNames: [],
    folderNamesExpanded: ["dist", "out", "build", "release", "bin"],
  },
  "folder-css": {
    iconPath: "./folder/css.svg",
    folderNames: ["css", "stylesheet", "stylesheets", "style", "styles"],
    folderNamesExpanded: [],
  },
  "folder-css-open": {
    iconPath: "./folder/css-open.svg",
    folderNames: [],
    folderNamesExpanded: ["css", "stylesheet", "stylesheets", "style", "styles"],
  },
  "folder-sass": {
    iconPath: "./folder/sass.svg",
    folderNames: ["sass", "_sass", "scss", "_scss"],
    folderNamesExpanded: [],
  },
  "folder-sass-open": {
    iconPath: "./folder/sass-open.svg",
    folderNames: [],
    folderNamesExpanded: ["sass", "_sass", "scss", "_scss"],
  },
  "folder-images": {
    iconPath: "./folder/images.svg",
    folderNames: [
      "_images",
      "_image",
      "_imgs",
      "_img",
      "images",
      "image",
      "imgs",
      "img",
      "icons",
      "icon",
      "icos",
      "ico",
      "figures",
      "figure",
      "figs",
      "fig",
      "screenshot",
      "screenshots",
      "screengrab",
      "screengrabs",
      "pic",
      "pics",
      "picture",
      "pictures",
    ],
    folderNamesExpanded: [],
  },
  "folder-images-open": {
    iconPath: "./folder/images-open.svg",
    folderNames: [],
    folderNamesExpanded: [
      "_images",
      "_image",
      "_imgs",
      "_img",
      "images",
      "image",
      "imgs",
      "img",
      "icons",
      "icon",
      "icos",
      "ico",
      "figures",
      "figure",
      "figs",
      "fig",
      "screenshot",
      "screenshots",
      "screengrab",
      "screengrabs",
      "pic",
      "pics",
      "picture",
      "pictures",
    ],
  },
  "folder-scripts": {
    iconPath: "./folder/scripts.svg",
    folderNames: ["script", "scripts"],
    folderNamesExpanded: [],
  },
  "folder-scripts-open": {
    iconPath: "./folder/scripts-open.svg",
    folderNames: [],
    folderNamesExpanded: ["script", "scripts"],
  },
  "folder-node": {
    iconPath: "./folder/node.svg",
    folderNames: ["node_modules"],
    folderNamesExpanded: [],
  },
  "folder-node-open": {
    iconPath: "./folder/node-open.svg",
    folderNames: [],
    folderNamesExpanded: ["node_modules"],
  },
  "folder-javascript": {
    iconPath: "./folder/javascript.svg",
    folderNames: ["js", "javascript", "javascripts"],
    folderNamesExpanded: [],
  },
  "folder-javascript-open": {
    iconPath: "./folder/javascript-open.svg",
    folderNames: [],
    folderNamesExpanded: ["js", "javascript", "javascripts"],
  },
  "folder-json": {
    iconPath: "./folder/json.svg",
    folderNames: ["json", "jsons"],
    folderNamesExpanded: [],
  },
  "folder-json-open": {
    iconPath: "./folder/json-open.svg",
    folderNames: [],
    folderNamesExpanded: ["json", "jsons"],
  },
  "folder-font": {
    iconPath: "./folder/font.svg",
    folderNames: ["font", "fonts"],
    folderNamesExpanded: [],
  },
  "folder-font-open": {
    iconPath: "./folder/font-open.svg",
    folderNames: [],
    folderNamesExpanded: ["font", "fonts"],
  },
  "folder-bower": {
    iconPath: "./folder/bower.svg",
    folderNames: ["bower_components"],
    folderNamesExpanded: [],
  },
  "folder-bower-open": {
    iconPath: "./folder/bower-open.svg",
    folderNames: [],
    folderNamesExpanded: ["bower_components"],
  },
  "folder-test": {
    iconPath: "./folder/test.svg",
    folderNames: ["test", "tests", "testing", "__tests__", "__snapshots__", "__mocks__", "__fixtures__", "__test__", "spec", "specs"],
    folderNamesExpanded: [],
  },
  "folder-test-open": {
    iconPath: "./folder/test-open.svg",
    folderNames: [],
    folderNamesExpanded: ["test", "tests", "testing", "__tests__", "__snapshots__", "__mocks__", "__fixtures__", "__test__", "spec", "specs"],
  },
  "folder-jinja": {
    iconPath: "./folder/jinja.svg",
    folderNames: ["jinja", "jinja2", "j2"],
    folderNamesExpanded: [],
  },
  "folder-jinja-open": {
    iconPath: "./folder/jinja-open.svg",
    folderNames: [],
    folderNamesExpanded: ["jinja", "jinja2", "j2"],
  },
  "folder-jinja_light": {
    iconPath: "./folder/jinja_light.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-jinja-open_light": {
    iconPath: "./folder/jinja-open_light.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-markdown": {
    iconPath: "./folder/markdown.svg",
    folderNames: ["markdown", "md"],
    folderNamesExpanded: [],
  },
  "folder-markdown-open": {
    iconPath: "./folder/markdown-open.svg",
    folderNames: [],
    folderNamesExpanded: ["markdown", "md"],
  },
  "folder-php": {
    iconPath: "./folder/php.svg",
    folderNames: ["php"],
    folderNamesExpanded: [],
  },
  "folder-php-open": {
    iconPath: "./folder/php-open.svg",
    folderNames: [],
    folderNamesExpanded: ["php"],
  },
  "folder-phpmailer": {
    iconPath: "./folder/phpmailer.svg",
    folderNames: ["phpmailer"],
    folderNamesExpanded: [],
  },
  "folder-phpmailer-open": {
    iconPath: "./folder/phpmailer-open.svg",
    folderNames: [],
    folderNamesExpanded: ["phpmailer"],
  },
  "folder-sublime": {
    iconPath: "./folder/sublime.svg",
    folderNames: ["sublime"],
    folderNamesExpanded: [],
  },
  "folder-sublime-open": {
    iconPath: "./folder/sublime-open.svg",
    folderNames: [],
    folderNamesExpanded: ["sublime"],
  },
  "folder-docs": {
    iconPath: "./folder/docs.svg",
    folderNames: ["_post", "_posts", "doc", "docs", "document", "documents", "documentation", "post", "posts", "article", "articles"],
    folderNamesExpanded: [],
  },
  "folder-docs-open": {
    iconPath: "./folder/docs-open.svg",
    folderNames: [],
    folderNamesExpanded: ["_post", "_posts", "doc", "docs", "document", "documents", "documentation", "post", "posts", "article", "articles"],
  },
  "folder-git": {
    iconPath: "./folder/git.svg",
    folderNames: [".git", "patches", "githooks", ".githooks", "submodules", ".submodules"],
    folderNamesExpanded: [],
  },
  "folder-git-open": {
    iconPath: "./folder/git-open.svg",
    folderNames: [],
    folderNamesExpanded: [".git", "patches", "githooks", ".githooks", "submodules", ".submodules"],
  },
  "folder-github": {
    iconPath: "./folder/github.svg",
    folderNames: [".github", "github"],
    folderNamesExpanded: [],
  },
  "folder-github-open": {
    iconPath: "./folder/github-open.svg",
    folderNames: [],
    folderNamesExpanded: [".github", "github"],
  },
  "folder-gitlab": {
    iconPath: "./folder/gitlab.svg",
    folderNames: [".gitlab"],
    folderNamesExpanded: [],
  },
  "folder-gitlab-open": {
    iconPath: "./folder/gitlab-open.svg",
    folderNames: [],
    folderNamesExpanded: [".gitlab"],
  },
  "folder-vscode": {
    iconPath: "./folder/vscode.svg",
    folderNames: [".vscode", ".vscode-test"],
    folderNamesExpanded: [],
  },
  "folder-vscode-open": {
    iconPath: "./folder/vscode-open.svg",
    folderNames: [],
    folderNamesExpanded: [".vscode", ".vscode-test"],
  },
  "folder-views": {
    iconPath: "./folder/views.svg",
    folderNames: ["view", "views", "screen", "screens", "page", "pages", "html"],
    folderNamesExpanded: [],
  },
  "folder-views-open": {
    iconPath: "./folder/views-open.svg",
    folderNames: [],
    folderNamesExpanded: ["view", "views", "screen", "screens", "page", "pages", "html"],
  },
  "folder-vue": {
    iconPath: "./folder/vue.svg",
    folderNames: ["vue"],
    folderNamesExpanded: [],
  },
  "folder-vue-open": {
    iconPath: "./folder/vue-open.svg",
    folderNames: [],
    folderNamesExpanded: ["vue"],
  },
  "folder-vuepress": {
    iconPath: "./folder/vuepress.svg",
    folderNames: [".vuepress"],
    folderNamesExpanded: [],
  },
  "folder-vuepress-open": {
    iconPath: "./folder/vuepress-open.svg",
    folderNames: [],
    folderNamesExpanded: [".vuepress"],
  },
  "folder-expo": {
    iconPath: "./folder/expo.svg",
    folderNames: [".expo", ".expo-shared"],
    folderNamesExpanded: [],
  },
  "folder-expo-open": {
    iconPath: "./folder/expo-open.svg",
    folderNames: [],
    folderNamesExpanded: [".expo", ".expo-shared"],
  },
  "folder-config": {
    iconPath: "./folder/config.svg",
    folderNames: ["cfg", "cfgs", "conf", "confs", "config", "configs", "configuration", "configurations", "setting", ".setting", "settings", ".settings", "META-INF"],
    folderNamesExpanded: [],
  },
  "folder-config-open": {
    iconPath: "./folder/config-open.svg",
    folderNames: [],
    folderNamesExpanded: ["cfg", "cfgs", "conf", "confs", "config", "configs", "configuration", "configurations", "setting", ".setting", "settings", ".settings", "META-INF"],
  },
  "folder-i18n": {
    iconPath: "./folder/i18n.svg",
    folderNames: ["i18n", "internationalization", "lang", "langs", "language", "languages", "locale", "locales", "l10n", "localization", "translation", "translate", "translations", ".tx"],
    folderNamesExpanded: [],
  },
  "folder-i18n-open": {
    iconPath: "./folder/i18n-open.svg",
    folderNames: [],
    folderNamesExpanded: ["i18n", "internationalization", "lang", "langs", "language", "languages", "locale", "locales", "l10n", "localization", "translation", "translate", "translations", ".tx"],
  },
  "folder-components": {
    iconPath: "./folder/components.svg",
    folderNames: ["components", "widget", "widgets", "fragments"],
    folderNamesExpanded: [],
  },
  "folder-components-open": {
    iconPath: "./folder/components-open.svg",
    folderNames: [],
    folderNamesExpanded: ["components", "widget", "widgets", "fragments"],
  },
  "folder-verdaccio": {
    iconPath: "./folder/verdaccio.svg",
    folderNames: [".verdaccio", "verdaccio"],
    folderNamesExpanded: [],
  },
  "folder-verdaccio-open": {
    iconPath: "./folder/verdaccio-open.svg",
    folderNames: [],
    folderNamesExpanded: [".verdaccio", "verdaccio"],
  },
  "folder-aurelia": {
    iconPath: "./folder/aurelia.svg",
    folderNames: ["aurelia_project"],
    folderNamesExpanded: [],
  },
  "folder-aurelia-open": {
    iconPath: "./folder/aurelia-open.svg",
    folderNames: [],
    folderNamesExpanded: ["aurelia_project"],
  },
  "folder-resource": {
    iconPath: "./folder/resource.svg",
    folderNames: ["resource", "resources", "res", "asset", "assets", "static", "report", "reports"],
    folderNamesExpanded: [],
  },
  "folder-resource-open": {
    iconPath: "./folder/resource-open.svg",
    folderNames: [],
    folderNamesExpanded: ["resource", "resources", "res", "asset", "assets", "static", "report", "reports"],
  },
  "folder-lib": {
    iconPath: "./folder/lib.svg",
    folderNames: ["lib", "libs", "library", "libraries", "vendor", "vendors", "third-party"],
    folderNamesExpanded: [],
  },
  "folder-lib-open": {
    iconPath: "./folder/lib-open.svg",
    folderNames: [],
    folderNamesExpanded: ["lib", "libs", "library", "libraries", "vendor", "vendors", "third-party"],
  },
  "folder-theme": {
    iconPath: "./folder/theme.svg",
    folderNames: ["themes", "theme", "color", "colors", "design", "designs"],
    folderNamesExpanded: [],
  },
  "folder-theme-open": {
    iconPath: "./folder/theme-open.svg",
    folderNames: [],
    folderNamesExpanded: ["themes", "theme", "color", "colors", "design", "designs"],
  },
  "folder-webpack": {
    iconPath: "./folder/webpack.svg",
    folderNames: ["webpack", ".webpack"],
    folderNamesExpanded: [],
  },
  "folder-webpack-open": {
    iconPath: "./folder/webpack-open.svg",
    folderNames: [],
    folderNamesExpanded: ["webpack", ".webpack"],
  },
  "folder-global": {
    iconPath: "./folder/global.svg",
    folderNames: ["global"],
    folderNamesExpanded: [],
  },
  "folder-global-open": {
    iconPath: "./folder/global-open.svg",
    folderNames: [],
    folderNamesExpanded: ["global"],
  },
  "folder-public": {
    iconPath: "./folder/public.svg",
    folderNames: ["_site", "public", "www", "wwwroot", "web", "website", "site", "browser", "browsers"],
    folderNamesExpanded: [],
  },
  "folder-public-open": {
    iconPath: "./folder/public-open.svg",
    folderNames: [],
    folderNamesExpanded: ["_site", "public", "www", "wwwroot", "web", "website", "site", "browser", "browsers"],
  },
  "folder-include": {
    iconPath: "./folder/include.svg",
    folderNames: ["include", "includes", "_includes", "inc", "partials", "_partials"],
    folderNamesExpanded: [],
  },
  "folder-include-open": {
    iconPath: "./folder/include-open.svg",
    folderNames: [],
    folderNamesExpanded: ["include", "includes", "_includes", "inc", "partials", "_partials"],
  },
  "folder-docker": {
    iconPath: "./folder/docker.svg",
    folderNames: ["docker", "dockerfiles", ".docker"],
    folderNamesExpanded: [],
  },
  "folder-docker-open": {
    iconPath: "./folder/docker-open.svg",
    folderNames: [],
    folderNamesExpanded: ["docker", "dockerfiles", ".docker"],
  },
  "folder-database": {
    iconPath: "./folder/database.svg",
    folderNames: ["db", "database", "databases", "sql", "data", "_data"],
    folderNamesExpanded: [],
  },
  "folder-database-open": {
    iconPath: "./folder/database-open.svg",
    folderNames: [],
    folderNamesExpanded: ["db", "database", "databases", "sql", "data", "_data"],
  },
  "folder-log": {
    iconPath: "./folder/log.svg",
    folderNames: ["log", "logs"],
    folderNamesExpanded: [],
  },
  "folder-log-open": {
    iconPath: "./folder/log-open.svg",
    folderNames: [],
    folderNamesExpanded: ["log", "logs"],
  },
  "folder-target": {
    iconPath: "./folder/target.svg",
    folderNames: ["target"],
    folderNamesExpanded: [],
  },
  "folder-target-open": {
    iconPath: "./folder/target-open.svg",
    folderNames: [],
    folderNamesExpanded: ["target"],
  },
  "folder-temp": {
    iconPath: "./folder/temp.svg",
    folderNames: ["temp", ".temp", "tmp", ".tmp", "cached", "cache", ".cache"],
    folderNamesExpanded: [],
  },
  "folder-temp-open": {
    iconPath: "./folder/temp-open.svg",
    folderNames: [],
    folderNamesExpanded: ["temp", ".temp", "tmp", ".tmp", "cached", "cache", ".cache"],
  },
  "folder-aws": {
    iconPath: "./folder/aws.svg",
    folderNames: ["aws", ".aws"],
    folderNamesExpanded: [],
  },
  "folder-aws-open": {
    iconPath: "./folder/aws-open.svg",
    folderNames: [],
    folderNamesExpanded: ["aws", ".aws"],
  },
  "folder-audio": {
    iconPath: "./folder/audio.svg",
    folderNames: ["aud", "auds", "audio", "audios", "music", "sound", "sounds"],
    folderNamesExpanded: [],
  },
  "folder-audio-open": {
    iconPath: "./folder/audio-open.svg",
    folderNames: [],
    folderNamesExpanded: ["aud", "auds", "audio", "audios", "music", "sound", "sounds"],
  },
  "folder-video": {
    iconPath: "./folder/video.svg",
    folderNames: ["vid", "vids", "video", "videos", "movie", "movies"],
    folderNamesExpanded: [],
  },
  "folder-video-open": {
    iconPath: "./folder/video-open.svg",
    folderNames: [],
    folderNamesExpanded: ["vid", "vids", "video", "videos", "movie", "movies"],
  },
  "folder-kubernetes": {
    iconPath: "./folder/kubernetes.svg",
    folderNames: ["kubernetes", ".kubernetes", "k8s", ".k8s"],
    folderNamesExpanded: [],
  },
  "folder-kubernetes-open": {
    iconPath: "./folder/kubernetes-open.svg",
    folderNames: [],
    folderNamesExpanded: ["kubernetes", ".kubernetes", "k8s", ".k8s"],
  },
  "folder-import": {
    iconPath: "./folder/import.svg",
    folderNames: ["import", "imports", "imported"],
    folderNamesExpanded: [],
  },
  "folder-import-open": {
    iconPath: "./folder/import-open.svg",
    folderNames: [],
    folderNamesExpanded: ["import", "imports", "imported"],
  },
  "folder-export": {
    iconPath: "./folder/export.svg",
    folderNames: ["export", "exports", "exported"],
    folderNamesExpanded: [],
  },
  "folder-export-open": {
    iconPath: "./folder/export-open.svg",
    folderNames: [],
    folderNamesExpanded: ["export", "exports", "exported"],
  },
  "folder-wakatime": {
    iconPath: "./folder/wakatime.svg",
    folderNames: ["wakatime"],
    folderNamesExpanded: [],
  },
  "folder-wakatime-open": {
    iconPath: "./folder/wakatime-open.svg",
    folderNames: [],
    folderNamesExpanded: ["wakatime"],
  },
  "folder-circleci": {
    iconPath: "./folder/circleci.svg",
    folderNames: [".circleci"],
    folderNamesExpanded: [],
  },
  "folder-circleci-open": {
    iconPath: "./folder/circleci-open.svg",
    folderNames: [],
    folderNamesExpanded: [".circleci"],
  },
  "folder-wordpress": {
    iconPath: "./folder/wordpress.svg",
    folderNames: [".wordpress-org", "wp-content"],
    folderNamesExpanded: [],
  },
  "folder-wordpress-open": {
    iconPath: "./folder/wordpress-open.svg",
    folderNames: [],
    folderNamesExpanded: [".wordpress-org", "wp-content"],
  },
  "folder-gradle": {
    iconPath: "./folder/gradle.svg",
    folderNames: ["gradle", ".gradle"],
    folderNamesExpanded: [],
  },
  "folder-gradle-open": {
    iconPath: "./folder/gradle-open.svg",
    folderNames: [],
    folderNamesExpanded: ["gradle", ".gradle"],
  },
  "folder-coverage": {
    iconPath: "./folder/coverage.svg",
    folderNames: ["coverage", ".nyc-output", ".nyc_output", "e2e", "it", "integration-test", "integration-tests", "__integration-test__", "__integration-tests__"],
    folderNamesExpanded: [],
  },
  "folder-coverage-open": {
    iconPath: "./folder/coverage-open.svg",
    folderNames: [],
    folderNamesExpanded: ["coverage", ".nyc-output", ".nyc_output", "e2e", "it", "integration-test", "integration-tests", "__integration-test__", "__integration-tests__"],
  },
  "folder-class": {
    iconPath: "./folder/class.svg",
    folderNames: ["class", "classes", "model", "models", "schemas", "schema"],
    folderNamesExpanded: [],
  },
  "folder-class-open": {
    iconPath: "./folder/class-open.svg",
    folderNames: [],
    folderNamesExpanded: ["class", "classes", "model", "models", "schemas", "schema"],
  },
  "folder-other": {
    iconPath: "./folder/other.svg",
    folderNames: ["other", "others", "misc", "miscellaneous", "extra", "extras", "etc"],
    folderNamesExpanded: [],
  },
  "folder-other-open": {
    iconPath: "./folder/other-open.svg",
    folderNames: [],
    folderNamesExpanded: ["other", "others", "misc", "miscellaneous", "extra", "extras", "etc"],
  },
  "folder-lua": {
    iconPath: "./folder/lua.svg",
    folderNames: ["lua"],
    folderNamesExpanded: [],
  },
  "folder-lua-open": {
    iconPath: "./folder/lua-open.svg",
    folderNames: [],
    folderNamesExpanded: ["lua"],
  },
  "folder-typescript": {
    iconPath: "./folder/typescript.svg",
    folderNames: ["typescript", "ts", "typings", "@types", "types"],
    folderNamesExpanded: [],
  },
  "folder-typescript-open": {
    iconPath: "./folder/typescript-open.svg",
    folderNames: [],
    folderNamesExpanded: ["typescript", "ts", "typings", "@types", "types"],
  },
  "folder-graphql": {
    iconPath: "./folder/graphql.svg",
    folderNames: ["graphql", "gql"],
    folderNamesExpanded: [],
  },
  "folder-graphql-open": {
    iconPath: "./folder/graphql-open.svg",
    folderNames: [],
    folderNamesExpanded: ["graphql", "gql"],
  },
  "folder-routes": {
    iconPath: "./folder/routes.svg",
    folderNames: ["routes", "router", "routers"],
    folderNamesExpanded: [],
  },
  "folder-routes-open": {
    iconPath: "./folder/routes-open.svg",
    folderNames: [],
    folderNamesExpanded: ["routes", "router", "routers"],
  },
  "folder-ci": {
    iconPath: "./folder/ci.svg",
    folderNames: [".ci", "ci"],
    folderNamesExpanded: [],
  },
  "folder-ci-open": {
    iconPath: "./folder/ci-open.svg",
    folderNames: [],
    folderNamesExpanded: [".ci", "ci"],
  },
  "folder-benchmark": {
    iconPath: "./folder/benchmark.svg",
    folderNames: ["benchmark", "benchmarks", "performance", "measure", "measures", "measurement"],
    folderNamesExpanded: [],
  },
  "folder-benchmark-open": {
    iconPath: "./folder/benchmark-open.svg",
    folderNames: [],
    folderNamesExpanded: ["benchmark", "benchmarks", "performance", "measure", "measures", "measurement"],
  },
  "folder-messages": {
    iconPath: "./folder/messages.svg",
    folderNames: ["messages", "messaging", "forum", "chat", "chats", "conversation", "conversations"],
    folderNamesExpanded: [],
  },
  "folder-messages-open": {
    iconPath: "./folder/messages-open.svg",
    folderNames: [],
    folderNamesExpanded: ["messages", "messaging", "forum", "chat", "chats", "conversation", "conversations"],
  },
  "folder-less": {
    iconPath: "./folder/less.svg",
    folderNames: ["less"],
    folderNamesExpanded: [],
  },
  "folder-less-open": {
    iconPath: "./folder/less-open.svg",
    folderNames: [],
    folderNamesExpanded: ["less"],
  },
  "folder-gulp": {
    iconPath: "./folder/gulp.svg",
    folderNames: ["gulp", "gulp-tasks", "gulpfile.js", "gulpfile.mjs", "gulpfile.ts", "gulpfile.babel.js"],
    folderNamesExpanded: [],
  },
  "folder-gulp-open": {
    iconPath: "./folder/gulp-open.svg",
    folderNames: [],
    folderNamesExpanded: ["gulp", "gulp-tasks", "gulpfile.js", "gulpfile.mjs", "gulpfile.ts", "gulpfile.babel.js"],
  },
  "folder-python": {
    iconPath: "./folder/python.svg",
    folderNames: ["python", "__pycache__", ".pytest_cache"],
    folderNamesExpanded: [],
  },
  "folder-python-open": {
    iconPath: "./folder/python-open.svg",
    folderNames: [],
    folderNamesExpanded: ["python", "__pycache__", ".pytest_cache"],
  },
  "folder-debug": {
    iconPath: "./folder/debug.svg",
    folderNames: ["debug", "debugging"],
    folderNamesExpanded: [],
  },
  "folder-debug-open": {
    iconPath: "./folder/debug-open.svg",
    folderNames: [],
    folderNamesExpanded: ["debug", "debugging"],
  },
  "folder-fastlane": {
    iconPath: "./folder/fastlane.svg",
    folderNames: ["fastlane"],
    folderNamesExpanded: [],
  },
  "folder-fastlane-open": {
    iconPath: "./folder/fastlane-open.svg",
    folderNames: [],
    folderNamesExpanded: ["fastlane"],
  },
  "folder-plugin": {
    iconPath: "./folder/plugin.svg",
    folderNames: ["plugin", "plugins", "_plugins", "extension", "extensions", "addon", "addons", "module", "modules"],
    folderNamesExpanded: [],
  },
  "folder-plugin-open": {
    iconPath: "./folder/plugin-open.svg",
    folderNames: [],
    folderNamesExpanded: ["plugin", "plugins", "_plugins", "extension", "extensions", "addon", "addons", "module", "modules"],
  },
  "folder-middleware": {
    iconPath: "./folder/middleware.svg",
    folderNames: ["middleware", "middlewares"],
    folderNamesExpanded: [],
  },
  "folder-middleware-open": {
    iconPath: "./folder/middleware-open.svg",
    folderNames: [],
    folderNamesExpanded: ["middleware", "middlewares"],
  },
  "folder-controller": {
    iconPath: "./folder/controller.svg",
    folderNames: ["controller", "controllers", "service", "services", "provider", "providers", "handler", "handlers"],
    folderNamesExpanded: [],
  },
  "folder-controller-open": {
    iconPath: "./folder/controller-open.svg",
    folderNames: [],
    folderNamesExpanded: ["controller", "controllers", "service", "services", "provider", "providers", "handler", "handlers"],
  },
  "folder-ansible": {
    iconPath: "./folder/ansible.svg",
    folderNames: ["ansible"],
    folderNamesExpanded: [],
  },
  "folder-ansible-open": {
    iconPath: "./folder/ansible-open.svg",
    folderNames: [],
    folderNamesExpanded: ["ansible"],
  },
  "folder-server": {
    iconPath: "./folder/server.svg",
    folderNames: ["server", "servers", "backend"],
    folderNamesExpanded: [],
  },
  "folder-server-open": {
    iconPath: "./folder/server-open.svg",
    folderNames: [],
    folderNamesExpanded: ["server", "servers", "backend"],
  },
  "folder-client": {
    iconPath: "./folder/client.svg",
    folderNames: ["client", "clients", "frontend", "pwa"],
    folderNamesExpanded: [],
  },
  "folder-client-open": {
    iconPath: "./folder/client-open.svg",
    folderNames: [],
    folderNamesExpanded: ["client", "clients", "frontend", "pwa"],
  },
  "folder-tasks": {
    iconPath: "./folder/tasks.svg",
    folderNames: ["tasks", "tickets"],
    folderNamesExpanded: [],
  },
  "folder-tasks-open": {
    iconPath: "./folder/tasks-open.svg",
    folderNames: [],
    folderNamesExpanded: ["tasks", "tickets"],
  },
  "folder-android": {
    iconPath: "./folder/android.svg",
    folderNames: ["android"],
    folderNamesExpanded: [],
  },
  "folder-android-open": {
    iconPath: "./folder/android-open.svg",
    folderNames: [],
    folderNamesExpanded: ["android"],
  },
  "folder-ios": {
    iconPath: "./folder/ios.svg",
    folderNames: ["ios"],
    folderNamesExpanded: [],
  },
  "folder-ios-open": {
    iconPath: "./folder/ios-open.svg",
    folderNames: [],
    folderNamesExpanded: ["ios"],
  },
  "folder-upload": {
    iconPath: "./folder/upload.svg",
    folderNames: ["uploads", "upload"],
    folderNamesExpanded: [],
  },
  "folder-upload-open": {
    iconPath: "./folder/upload-open.svg",
    folderNames: [],
    folderNamesExpanded: ["uploads", "upload"],
  },
  "folder-download": {
    iconPath: "./folder/download.svg",
    folderNames: ["downloads", "download"],
    folderNamesExpanded: [],
  },
  "folder-download-open": {
    iconPath: "./folder/download-open.svg",
    folderNames: [],
    folderNamesExpanded: ["downloads", "download"],
  },
  "folder-tools": {
    iconPath: "./folder/tools.svg",
    folderNames: ["tools", "toolkit", "toolkits", "toolbox", "toolboxes"],
    folderNamesExpanded: [],
  },
  "folder-tools-open": {
    iconPath: "./folder/tools-open.svg",
    folderNames: [],
    folderNamesExpanded: ["tools", "toolkit", "toolkits", "toolbox", "toolboxes"],
  },
  "folder-helper": {
    iconPath: "./folder/helper.svg",
    folderNames: ["helpers", "helper"],
    folderNamesExpanded: [],
  },
  "folder-helper-open": {
    iconPath: "./folder/helper-open.svg",
    folderNames: [],
    folderNamesExpanded: ["helpers", "helper"],
  },
  "folder-serverless": {
    iconPath: "./folder/serverless.svg",
    folderNames: [".serverless", "serverless"],
    folderNamesExpanded: [],
  },
  "folder-serverless-open": {
    iconPath: "./folder/serverless-open.svg",
    folderNames: [],
    folderNamesExpanded: [".serverless", "serverless"],
  },
  "folder-api": {
    iconPath: "./folder/api.svg",
    folderNames: ["api", "apis", "restapi"],
    folderNamesExpanded: [],
  },
  "folder-api-open": {
    iconPath: "./folder/api-open.svg",
    folderNames: [],
    folderNamesExpanded: ["api", "apis", "restapi"],
  },
  "folder-app": {
    iconPath: "./folder/app.svg",
    folderNames: ["app", "apps"],
    folderNamesExpanded: [],
  },
  "folder-app-open": {
    iconPath: "./folder/app-open.svg",
    folderNames: [],
    folderNamesExpanded: ["app", "apps"],
  },
  "folder-apollo": {
    iconPath: "./folder/apollo.svg",
    folderNames: ["apollo", "apollo-client", "apollo-cache", "apollo-config"],
    folderNamesExpanded: [],
  },
  "folder-apollo-open": {
    iconPath: "./folder/apollo-open.svg",
    folderNames: [],
    folderNamesExpanded: ["apollo", "apollo-client", "apollo-cache", "apollo-config"],
  },
  "folder-archive": {
    iconPath: "./folder/archive.svg",
    folderNames: ["arc", "arcs", "archive", "archives", "archival", "bkp", "bkps", "bak", "baks", "backup", "backups", "back-up", "back-ups"],
    folderNamesExpanded: [],
  },
  "folder-archive-open": {
    iconPath: "./folder/archive-open.svg",
    folderNames: [],
    folderNamesExpanded: ["arc", "arcs", "archive", "archives", "archival", "bkp", "bkps", "bak", "baks", "backup", "backups", "back-up", "back-ups"],
  },
  "folder-batch": {
    iconPath: "./folder/batch.svg",
    folderNames: ["batch", "batchs", "batches"],
    folderNamesExpanded: [],
  },
  "folder-batch-open": {
    iconPath: "./folder/batch-open.svg",
    folderNames: [],
    folderNamesExpanded: ["batch", "batchs", "batches"],
  },
  "folder-buildkite": {
    iconPath: "./folder/buildkite.svg",
    folderNames: ["buildkite", ".buildkite"],
    folderNamesExpanded: [],
  },
  "folder-buildkite-open": {
    iconPath: "./folder/buildkite-open.svg",
    folderNames: [],
    folderNamesExpanded: ["buildkite", ".buildkite"],
  },
  "folder-cluster": {
    iconPath: "./folder/cluster.svg",
    folderNames: ["cluster", "clusters"],
    folderNamesExpanded: [],
  },
  "folder-cluster-open": {
    iconPath: "./folder/cluster-open.svg",
    folderNames: [],
    folderNamesExpanded: ["cluster", "clusters"],
  },
  "folder-command": {
    iconPath: "./folder/command.svg",
    folderNames: ["command", "commands", "cmd", "cli", "clis"],
    folderNamesExpanded: [],
  },
  "folder-command-open": {
    iconPath: "./folder/command-open.svg",
    folderNames: [],
    folderNamesExpanded: ["command", "commands", "cmd", "cli", "clis"],
  },
  "folder-constant": {
    iconPath: "./folder/constant.svg",
    folderNames: ["constant", "constants"],
    folderNamesExpanded: [],
  },
  "folder-constant-open": {
    iconPath: "./folder/constant-open.svg",
    folderNames: [],
    folderNamesExpanded: ["constant", "constants"],
  },
  "folder-container": {
    iconPath: "./folder/container.svg",
    folderNames: ["container", "containers", ".devcontainer"],
    folderNamesExpanded: [],
  },
  "folder-container-open": {
    iconPath: "./folder/container-open.svg",
    folderNames: [],
    folderNamesExpanded: ["container", "containers", ".devcontainer"],
  },
  "folder-content": {
    iconPath: "./folder/content.svg",
    folderNames: ["content", "contents"],
    folderNamesExpanded: [],
  },
  "folder-content-open": {
    iconPath: "./folder/content-open.svg",
    folderNames: [],
    folderNamesExpanded: ["content", "contents"],
  },
  "folder-context": {
    iconPath: "./folder/context.svg",
    folderNames: ["context", "contexts"],
    folderNamesExpanded: [],
  },
  "folder-context-open": {
    iconPath: "./folder/context-open.svg",
    folderNames: [],
    folderNamesExpanded: ["context", "contexts"],
  },
  "folder-core": {
    iconPath: "./folder/core.svg",
    folderNames: ["core"],
    folderNamesExpanded: [],
  },
  "folder-core-open": {
    iconPath: "./folder/core-open.svg",
    folderNames: [],
    folderNamesExpanded: ["core"],
  },
  "folder-delta": {
    iconPath: "./folder/delta.svg",
    folderNames: ["delta", "deltas", "changes"],
    folderNamesExpanded: [],
  },
  "folder-delta-open": {
    iconPath: "./folder/delta-open.svg",
    folderNames: [],
    folderNamesExpanded: ["delta", "deltas", "changes"],
  },
  "folder-dump": {
    iconPath: "./folder/dump.svg",
    folderNames: ["dump", "dumps"],
    folderNamesExpanded: [],
  },
  "folder-dump-open": {
    iconPath: "./folder/dump-open.svg",
    folderNames: [],
    folderNamesExpanded: ["dump", "dumps"],
  },
  "folder-examples": {
    iconPath: "./folder/examples.svg",
    folderNames: ["demo", "demos", "example", "examples", "sample", "samples", "sample-data"],
    folderNamesExpanded: [],
  },
  "folder-examples-open": {
    iconPath: "./folder/examples-open.svg",
    folderNames: [],
    folderNamesExpanded: ["demo", "demos", "example", "examples", "sample", "samples", "sample-data"],
  },
  "folder-environment": {
    iconPath: "./folder/environment.svg",
    folderNames: [".env", ".environment", "env", "envs", "environment", "environments", ".venv"],
    folderNamesExpanded: [],
  },
  "folder-environment-open": {
    iconPath: "./folder/environment-open.svg",
    folderNames: [],
    folderNamesExpanded: [".env", ".environment", "env", "envs", "environment", "environments", ".venv"],
  },
  "folder-functions": {
    iconPath: "./folder/functions.svg",
    folderNames: ["func", "funcs", "function", "functions", "lambda", "lambdas", "logic", "math", "maths", "calc", "calcs", "calculation", "calculations"],
    folderNamesExpanded: [],
  },
  "folder-functions-open": {
    iconPath: "./folder/functions-open.svg",
    folderNames: [],
    folderNamesExpanded: ["func", "funcs", "function", "functions", "lambda", "lambdas", "logic", "math", "maths", "calc", "calcs", "calculation", "calculations"],
  },
  "folder-generator": {
    iconPath: "./folder/generator.svg",
    folderNames: ["generator", "generators", "generated", "cfn-gen", "gen", "gens", "auto"],
    folderNamesExpanded: [],
  },
  "folder-generator-open": {
    iconPath: "./folder/generator-open.svg",
    folderNames: [],
    folderNamesExpanded: ["generator", "generators", "generated", "cfn-gen", "gen", "gens", "auto"],
  },
  "folder-hook": {
    iconPath: "./folder/hook.svg",
    folderNames: ["hook", "hooks", "trigger", "triggers"],
    folderNamesExpanded: [],
  },
  "folder-hook-open": {
    iconPath: "./folder/hook-open.svg",
    folderNames: [],
    folderNamesExpanded: ["hook", "hooks", "trigger", "triggers"],
  },
  "folder-job": {
    iconPath: "./folder/job.svg",
    folderNames: ["job", "jobs"],
    folderNamesExpanded: [],
  },
  "folder-job-open": {
    iconPath: "./folder/job-open.svg",
    folderNames: [],
    folderNamesExpanded: ["job", "jobs"],
  },
  "folder-keys": {
    iconPath: "./folder/keys.svg",
    folderNames: ["keys", "key", "token", "tokens", "jwt"],
    folderNamesExpanded: [],
  },
  "folder-keys-open": {
    iconPath: "./folder/keys-open.svg",
    folderNames: [],
    folderNamesExpanded: ["keys", "key", "token", "tokens", "jwt"],
  },
  "folder-layout": {
    iconPath: "./folder/layout.svg",
    folderNames: ["layout", "layouts", "_layouts"],
    folderNamesExpanded: [],
  },
  "folder-layout-open": {
    iconPath: "./folder/layout-open.svg",
    folderNames: [],
    folderNamesExpanded: ["layout", "layouts", "_layouts"],
  },
  "folder-mail": {
    iconPath: "./folder/mail.svg",
    folderNames: ["mail", "mails", "email", "emails", "smtp", "mailers"],
    folderNamesExpanded: [],
  },
  "folder-mail-open": {
    iconPath: "./folder/mail-open.svg",
    folderNames: [],
    folderNamesExpanded: ["mail", "mails", "email", "emails", "smtp", "mailers"],
  },
  "folder-mappings": {
    iconPath: "./folder/mappings.svg",
    folderNames: ["mappings", "mapping"],
    folderNamesExpanded: [],
  },
  "folder-mappings-open": {
    iconPath: "./folder/mappings-open.svg",
    folderNames: [],
    folderNamesExpanded: ["mappings", "mapping"],
  },
  "folder-meta": {
    iconPath: "./folder/meta.svg",
    folderNames: ["meta"],
    folderNamesExpanded: [],
  },
  "folder-meta-open": {
    iconPath: "./folder/meta-open.svg",
    folderNames: [],
    folderNamesExpanded: ["meta"],
  },
  "folder-changesets": {
    iconPath: "./folder/changesets.svg",
    folderNames: [".changesets", ".changeset"],
    folderNamesExpanded: [],
  },
  "folder-changesets-open": {
    iconPath: "./folder/changesets-open.svg",
    folderNames: [],
    folderNamesExpanded: [".changesets", ".changeset"],
  },
  "folder-packages": {
    iconPath: "./folder/packages.svg",
    folderNames: ["package", "packages", "pkg", "pkgs"],
    folderNamesExpanded: [],
  },
  "folder-packages-open": {
    iconPath: "./folder/packages-open.svg",
    folderNames: [],
    folderNamesExpanded: ["package", "packages", "pkg", "pkgs"],
  },
  "folder-shared": {
    iconPath: "./folder/shared.svg",
    folderNames: ["shared", "common"],
    folderNamesExpanded: [],
  },
  "folder-shared-open": {
    iconPath: "./folder/shared-open.svg",
    folderNames: [],
    folderNamesExpanded: ["shared", "common"],
  },
  "folder-shader": {
    iconPath: "./folder/shader.svg",
    folderNames: ["glsl", "hlsl", "shader", "shaders"],
    folderNamesExpanded: [],
  },
  "folder-shader-open": {
    iconPath: "./folder/shader-open.svg",
    folderNames: [],
    folderNamesExpanded: ["glsl", "hlsl", "shader", "shaders"],
  },
  "folder-stack": {
    iconPath: "./folder/stack.svg",
    folderNames: ["stack", "stacks"],
    folderNamesExpanded: [],
  },
  "folder-stack-open": {
    iconPath: "./folder/stack-open.svg",
    folderNames: [],
    folderNamesExpanded: ["stack", "stacks"],
  },
  "folder-template": {
    iconPath: "./folder/template.svg",
    folderNames: ["template", "templates"],
    folderNamesExpanded: [],
  },
  "folder-template-open": {
    iconPath: "./folder/template-open.svg",
    folderNames: [],
    folderNamesExpanded: ["template", "templates"],
  },
  "folder-utils": {
    iconPath: "./folder/utils.svg",
    folderNames: ["util", "utils", "utility", "utilities"],
    folderNamesExpanded: [],
  },
  "folder-utils-open": {
    iconPath: "./folder/utils-open.svg",
    folderNames: [],
    folderNamesExpanded: ["util", "utils", "utility", "utilities"],
  },
  "folder-supabase": {
    iconPath: "./folder/supabase.svg",
    folderNames: ["supabase", ".supabase"],
    folderNamesExpanded: [],
  },
  "folder-supabase-open": {
    iconPath: "./folder/supabase-open.svg",
    folderNames: [],
    folderNamesExpanded: ["supabase", ".supabase"],
  },
  "folder-private": {
    iconPath: "./folder/private.svg",
    folderNames: ["private", ".private"],
    folderNamesExpanded: [],
  },
  "folder-private-open": {
    iconPath: "./folder/private-open.svg",
    folderNames: [],
    folderNamesExpanded: ["private", ".private"],
  },
  "folder-error": {
    iconPath: "./folder/error.svg",
    folderNames: ["error", "errors", "err"],
    folderNamesExpanded: [],
  },
  "folder-error-open": {
    iconPath: "./folder/error-open.svg",
    folderNames: [],
    folderNamesExpanded: ["error", "errors", "err"],
  },
  "folder-event": {
    iconPath: "./folder/event.svg",
    folderNames: ["event", "events"],
    folderNamesExpanded: [],
  },
  "folder-event-open": {
    iconPath: "./folder/event-open.svg",
    folderNames: [],
    folderNamesExpanded: ["event", "events"],
  },
  "folder-secure": {
    iconPath: "./folder/secure.svg",
    folderNames: ["auth", "authentication", "secure", "security", "cert", "certs", "certificate", "certificates", "ssl"],
    folderNamesExpanded: [],
  },
  "folder-secure-open": {
    iconPath: "./folder/secure-open.svg",
    folderNames: [],
    folderNamesExpanded: ["auth", "authentication", "secure", "security", "cert", "certs", "certificate", "certificates", "ssl"],
  },
  "folder-custom": {
    iconPath: "./folder/custom.svg",
    folderNames: ["custom", "customs"],
    folderNamesExpanded: [],
  },
  "folder-custom-open": {
    iconPath: "./folder/custom-open.svg",
    folderNames: [],
    folderNamesExpanded: ["custom", "customs"],
  },
  "folder-mock": {
    iconPath: "./folder/mock.svg",
    folderNames: ["_draft", "_drafts", "mock", "mocks", "fixture", "fixtures", "draft", "drafts", "concept", "concepts", "sketch", "sketches"],
    folderNamesExpanded: [],
  },
  "folder-mock-open": {
    iconPath: "./folder/mock-open.svg",
    folderNames: [],
    folderNamesExpanded: ["_draft", "_drafts", "mock", "mocks", "fixture", "fixtures", "draft", "drafts", "concept", "concepts", "sketch", "sketches"],
  },
  "folder-syntax": {
    iconPath: "./folder/syntax.svg",
    folderNames: ["syntax", "syntaxes", "spellcheck"],
    folderNamesExpanded: [],
  },
  "folder-syntax-open": {
    iconPath: "./folder/syntax-open.svg",
    folderNames: [],
    folderNamesExpanded: ["syntax", "syntaxes", "spellcheck"],
  },
  "folder-vm": {
    iconPath: "./folder/vm.svg",
    folderNames: ["vm", "vms"],
    folderNamesExpanded: [],
  },
  "folder-vm-open": {
    iconPath: "./folder/vm-open.svg",
    folderNames: [],
    folderNamesExpanded: ["vm", "vms"],
  },
  "folder-stylus": {
    iconPath: "./folder/stylus.svg",
    folderNames: ["stylus"],
    folderNamesExpanded: [],
  },
  "folder-stylus-open": {
    iconPath: "./folder/stylus-open.svg",
    folderNames: [],
    folderNamesExpanded: ["stylus"],
  },
  "folder-flow": {
    iconPath: "./folder/flow.svg",
    folderNames: ["flow-typed"],
    folderNamesExpanded: [],
  },
  "folder-flow-open": {
    iconPath: "./folder/flow-open.svg",
    folderNames: [],
    folderNamesExpanded: ["flow-typed"],
  },
  "folder-rules": {
    iconPath: "./folder/rules.svg",
    folderNames: ["rule", "rules", "validation", "validations", "validator", "validators"],
    folderNamesExpanded: [],
  },
  "folder-rules-open": {
    iconPath: "./folder/rules-open.svg",
    folderNames: [],
    folderNamesExpanded: ["rule", "rules", "validation", "validations", "validator", "validators"],
  },
  "folder-review": {
    iconPath: "./folder/review.svg",
    folderNames: ["review", "reviews", "revisal", "revisals", "reviewed"],
    folderNamesExpanded: [],
  },
  "folder-review-open": {
    iconPath: "./folder/review-open.svg",
    folderNames: [],
    folderNamesExpanded: ["review", "reviews", "revisal", "revisals", "reviewed"],
  },
  "folder-animation": {
    iconPath: "./folder/animation.svg",
    folderNames: ["anim", "anims", "animation", "animations", "animated"],
    folderNamesExpanded: [],
  },
  "folder-animation-open": {
    iconPath: "./folder/animation-open.svg",
    folderNames: [],
    folderNamesExpanded: ["anim", "anims", "animation", "animations", "animated"],
  },
  "folder-guard": {
    iconPath: "./folder/guard.svg",
    folderNames: ["guard", "guards"],
    folderNamesExpanded: [],
  },
  "folder-guard-open": {
    iconPath: "./folder/guard-open.svg",
    folderNames: [],
    folderNamesExpanded: ["guard", "guards"],
  },
  "folder-prisma": {
    iconPath: "./folder/prisma.svg",
    folderNames: ["prisma"],
    folderNamesExpanded: [],
  },
  "folder-prisma-open": {
    iconPath: "./folder/prisma-open.svg",
    folderNames: [],
    folderNamesExpanded: ["prisma"],
  },
  "folder-pipe": {
    iconPath: "./folder/pipe.svg",
    folderNames: ["pipe", "pipes"],
    folderNamesExpanded: [],
  },
  "folder-pipe-open": {
    iconPath: "./folder/pipe-open.svg",
    folderNames: [],
    folderNamesExpanded: ["pipe", "pipes"],
  },
  "folder-svg": {
    iconPath: "./folder/svg.svg",
    folderNames: ["svg", "svgs"],
    folderNamesExpanded: [],
  },
  "folder-svg-open": {
    iconPath: "./folder/svg-open.svg",
    folderNames: [],
    folderNamesExpanded: ["svg", "svgs"],
  },
  "folder-terraform": {
    iconPath: "./folder/terraform.svg",
    folderNames: ["terraform", ".terraform"],
    folderNamesExpanded: [],
  },
  "folder-terraform-open": {
    iconPath: "./folder/terraform-open.svg",
    folderNames: [],
    folderNamesExpanded: ["terraform", ".terraform"],
  },
  "folder-mobile": {
    iconPath: "./folder/mobile.svg",
    folderNames: ["mobile", "mobiles", "portable", "portability"],
    folderNamesExpanded: [],
  },
  "folder-mobile-open": {
    iconPath: "./folder/mobile-open.svg",
    folderNames: [],
    folderNamesExpanded: ["mobile", "mobiles", "portable", "portability"],
  },
  "folder-stencil": {
    iconPath: "./folder/stencil.svg",
    folderNames: [".stencil"],
    folderNamesExpanded: [],
  },
  "folder-stencil-open": {
    iconPath: "./folder/stencil-open.svg",
    folderNames: [],
    folderNamesExpanded: [".stencil"],
  },
  "folder-firebase": {
    iconPath: "./folder/firebase.svg",
    folderNames: ["firebase", ".firebase"],
    folderNamesExpanded: [],
  },
  "folder-firebase-open": {
    iconPath: "./folder/firebase-open.svg",
    folderNames: [],
    folderNamesExpanded: ["firebase", ".firebase"],
  },
  "folder-svelte": {
    iconPath: "./folder/svelte.svg",
    folderNames: ["svelte", ".svelte-kit"],
    folderNamesExpanded: [],
  },
  "folder-svelte-open": {
    iconPath: "./folder/svelte-open.svg",
    folderNames: [],
    folderNamesExpanded: ["svelte", ".svelte-kit"],
  },
  "folder-update": {
    iconPath: "./folder/update.svg",
    folderNames: ["update", "updates", "upgrade", "upgrades"],
    folderNamesExpanded: [],
  },
  "folder-update-open": {
    iconPath: "./folder/update-open.svg",
    folderNames: [],
    folderNamesExpanded: ["update", "updates", "upgrade", "upgrades"],
  },
  "folder-intellij": {
    iconPath: "./folder/intellij.svg",
    folderNames: [".idea"],
    folderNamesExpanded: [],
  },
  "folder-intellij-open": {
    iconPath: "./folder/intellij-open.svg",
    folderNames: [],
    folderNamesExpanded: [".idea"],
  },
  "folder-intellij_light": {
    iconPath: "./folder/intellij_light.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-intellij-open_light": {
    iconPath: "./folder/intellij-open_light.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-azure-pipelines": {
    iconPath: "./folder/azure-pipelines.svg",
    folderNames: [".azure-pipelines", ".azure-pipelines-ci"],
    folderNamesExpanded: [],
  },
  "folder-azure-pipelines-open": {
    iconPath: "./folder/azure-pipelines-open.svg",
    folderNames: [],
    folderNamesExpanded: [".azure-pipelines", ".azure-pipelines-ci"],
  },
  "folder-mjml": {
    iconPath: "./folder/mjml.svg",
    folderNames: ["mjml"],
    folderNamesExpanded: [],
  },
  "folder-mjml-open": {
    iconPath: "./folder/mjml-open.svg",
    folderNames: [],
    folderNamesExpanded: ["mjml"],
  },
  "folder-admin": {
    iconPath: "./folder/admin.svg",
    folderNames: ["admin", "manager", "moderator"],
    folderNamesExpanded: [],
  },
  "folder-admin-open": {
    iconPath: "./folder/admin-open.svg",
    folderNames: [],
    folderNamesExpanded: ["admin", "manager", "moderator"],
  },
  "folder-scala": {
    iconPath: "./folder/scala.svg",
    folderNames: ["scala"],
    folderNamesExpanded: [],
  },
  "folder-scala-open": {
    iconPath: "./folder/scala-open.svg",
    folderNames: [],
    folderNamesExpanded: ["scala"],
  },
  "folder-connection": {
    iconPath: "./folder/connection.svg",
    folderNames: ["connection", "connections", "integration", "integrations"],
    folderNamesExpanded: [],
  },
  "folder-connection-open": {
    iconPath: "./folder/connection-open.svg",
    folderNames: [],
    folderNamesExpanded: ["connection", "connections", "integration", "integrations"],
  },
  "folder-quasar": {
    iconPath: "./folder/quasar.svg",
    folderNames: [".quasar"],
    folderNamesExpanded: [],
  },
  "folder-quasar-open": {
    iconPath: "./folder/quasar-open.svg",
    folderNames: [],
    folderNamesExpanded: [".quasar"],
  },
  "folder-next": {
    iconPath: "./folder/next.svg",
    folderNames: [".next"],
    folderNamesExpanded: [],
  },
  "folder-next-open": {
    iconPath: "./folder/next-open.svg",
    folderNames: [],
    folderNamesExpanded: [".next"],
  },
  "folder-cobol": {
    iconPath: "./folder/cobol.svg",
    folderNames: ["cobol"],
    folderNamesExpanded: [],
  },
  "folder-cobol-open": {
    iconPath: "./folder/cobol-open.svg",
    folderNames: [],
    folderNamesExpanded: ["cobol"],
  },
  "folder-yarn": {
    iconPath: "./folder/yarn.svg",
    folderNames: ["yarn", ".yarn"],
    folderNamesExpanded: [],
  },
  "folder-yarn-open": {
    iconPath: "./folder/yarn-open.svg",
    folderNames: [],
    folderNamesExpanded: ["yarn", ".yarn"],
  },
  "folder-husky": {
    iconPath: "./folder/husky.svg",
    folderNames: ["husky", ".husky"],
    folderNamesExpanded: [],
  },
  "folder-husky-open": {
    iconPath: "./folder/husky-open.svg",
    folderNames: [],
    folderNamesExpanded: ["husky", ".husky"],
  },
  "folder-storybook": {
    iconPath: "./folder/storybook.svg",
    folderNames: [".storybook", "storybook", "stories", "__stories__"],
    folderNamesExpanded: [],
  },
  "folder-storybook-open": {
    iconPath: "./folder/storybook-open.svg",
    folderNames: [],
    folderNamesExpanded: [".storybook", "storybook", "stories", "__stories__"],
  },
  "folder-base": {
    iconPath: "./folder/base.svg",
    folderNames: ["base", ".base", "bases"],
    folderNamesExpanded: [],
  },
  "folder-base-open": {
    iconPath: "./folder/base-open.svg",
    folderNames: [],
    folderNamesExpanded: ["base", ".base", "bases"],
  },
  "folder-cart": {
    iconPath: "./folder/cart.svg",
    folderNames: ["cart", "shopping-cart", "shopping", "shop"],
    folderNamesExpanded: [],
  },
  "folder-cart-open": {
    iconPath: "./folder/cart-open.svg",
    folderNames: [],
    folderNamesExpanded: ["cart", "shopping-cart", "shopping", "shop"],
  },
  "folder-home": {
    iconPath: "./folder/home.svg",
    folderNames: ["home", ".home", "start", ".start"],
    folderNamesExpanded: [],
  },
  "folder-home-open": {
    iconPath: "./folder/home-open.svg",
    folderNames: [],
    folderNamesExpanded: ["home", ".home", "start", ".start"],
  },
  "folder-project": {
    iconPath: "./folder/project.svg",
    folderNames: ["project", "projects", ".project", ".projects"],
    folderNamesExpanded: [],
  },
  "folder-project-open": {
    iconPath: "./folder/project-open.svg",
    folderNames: [],
    folderNamesExpanded: ["project", "projects", ".project", ".projects"],
  },
  "folder-interface": {
    iconPath: "./folder/interface.svg",
    folderNames: ["interface", "interfaces"],
    folderNamesExpanded: [],
  },
  "folder-interface-open": {
    iconPath: "./folder/interface-open.svg",
    folderNames: [],
    folderNamesExpanded: ["interface", "interfaces"],
  },
  "folder-netlify": {
    iconPath: "./folder/netlify.svg",
    folderNames: [".netlify"],
    folderNamesExpanded: [],
  },
  "folder-netlify-open": {
    iconPath: "./folder/netlify-open.svg",
    folderNames: [],
    folderNamesExpanded: [".netlify"],
  },
  "folder-contract": {
    iconPath: "./folder/contract.svg",
    folderNames: ["pact", "pacts", "contract", ".contract", "contracts", "contract-testing", "contract-test", "contract-tests"],
    folderNamesExpanded: [],
  },
  "folder-contract-open": {
    iconPath: "./folder/contract-open.svg",
    folderNames: [],
    folderNamesExpanded: ["pact", "pacts", "contract", ".contract", "contracts", "contract-testing", "contract-test", "contract-tests"],
  },
  "folder-queue": {
    iconPath: "./folder/queue.svg",
    folderNames: ["queue", "queues", "bull", "mq"],
    folderNamesExpanded: [],
  },
  "folder-queue-open": {
    iconPath: "./folder/queue-open.svg",
    folderNames: [],
    folderNamesExpanded: ["queue", "queues", "bull", "mq"],
  },
  "folder-vercel": {
    iconPath: "./folder/vercel.svg",
    folderNames: ["vercel", ".vercel", "now", ".now"],
    folderNamesExpanded: [],
  },
  "folder-vercel-open": {
    iconPath: "./folder/vercel-open.svg",
    folderNames: [],
    folderNamesExpanded: ["vercel", ".vercel", "now", ".now"],
  },
  "folder-cypress": {
    iconPath: "./folder/cypress.svg",
    folderNames: ["cypress", ".cypress"],
    folderNamesExpanded: [],
  },
  "folder-cypress-open": {
    iconPath: "./folder/cypress-open.svg",
    folderNames: [],
    folderNamesExpanded: ["cypress", ".cypress"],
  },
  "folder-decorators": {
    iconPath: "./folder/decorators.svg",
    folderNames: ["decorator", "decorators"],
    folderNamesExpanded: [],
  },
  "folder-decorators-open": {
    iconPath: "./folder/decorators-open.svg",
    folderNames: [],
    folderNamesExpanded: ["decorator", "decorators"],
  },
  "folder-java": {
    iconPath: "./folder/java.svg",
    folderNames: ["java"],
    folderNamesExpanded: [],
  },
  "folder-java-open": {
    iconPath: "./folder/java-open.svg",
    folderNames: [],
    folderNamesExpanded: ["java"],
  },
  "folder-resolver": {
    iconPath: "./folder/resolver.svg",
    folderNames: ["resolver", "resolvers"],
    folderNamesExpanded: [],
  },
  "folder-resolver-open": {
    iconPath: "./folder/resolver-open.svg",
    folderNames: [],
    folderNamesExpanded: ["resolver", "resolvers"],
  },
  "folder-angular": {
    iconPath: "./folder/angular.svg",
    folderNames: ["angular", ".angular"],
    folderNamesExpanded: [],
  },
  "folder-angular-open": {
    iconPath: "./folder/angular-open.svg",
    folderNames: [],
    folderNamesExpanded: ["angular", ".angular"],
  },
  "folder-unity": {
    iconPath: "./folder/unity.svg",
    folderNames: ["unity"],
    folderNamesExpanded: [],
  },
  "folder-unity-open": {
    iconPath: "./folder/unity-open.svg",
    folderNames: [],
    folderNamesExpanded: ["unity"],
  },
  "folder-pdf": {
    iconPath: "./folder/pdf.svg",
    folderNames: ["pdf", "pdfs"],
    folderNamesExpanded: [],
  },
  "folder-pdf-open": {
    iconPath: "./folder/pdf-open.svg",
    folderNames: [],
    folderNamesExpanded: ["pdf", "pdfs"],
  },
  "folder-proto": {
    iconPath: "./folder/proto.svg",
    folderNames: ["protobufs", "proto"],
    folderNamesExpanded: [],
  },
  "folder-proto-open": {
    iconPath: "./folder/proto-open.svg",
    folderNames: [],
    folderNamesExpanded: ["protobufs", "proto"],
  },
  "folder-plastic": {
    iconPath: "./folder/plastic.svg",
    folderNames: ["plastic", ".plastic"],
    folderNamesExpanded: [],
  },
  "folder-plastic-open": {
    iconPath: "./folder/plastic-open.svg",
    folderNames: [],
    folderNamesExpanded: ["plastic", ".plastic"],
  },
  "folder-gamemaker": {
    iconPath: "./folder/gamemaker.svg",
    folderNames: ["gamemaker", "gamemaker2"],
    folderNamesExpanded: [],
  },
  "folder-gamemaker-open": {
    iconPath: "./folder/gamemaker-open.svg",
    folderNames: [],
    folderNamesExpanded: ["gamemaker", "gamemaker2"],
  },
  "folder-mercurial": {
    iconPath: "./folder/mercurial.svg",
    folderNames: [".hg", "hghooks", ".hghooks", ".hgext"],
    folderNamesExpanded: [],
  },
  "folder-mercurial-open": {
    iconPath: "./folder/mercurial-open.svg",
    folderNames: [],
    folderNamesExpanded: [".hg", "hghooks", ".hghooks", ".hgext"],
  },
  "folder-godot": {
    iconPath: "./folder/godot.svg",
    folderNames: ["godot", ".godot", "godot-cpp", ".godot-cpp"],
    folderNamesExpanded: [],
  },
  "folder-godot-open": {
    iconPath: "./folder/godot-open.svg",
    folderNames: [],
    folderNamesExpanded: ["godot", ".godot", "godot-cpp", ".godot-cpp"],
  },
  folder: {
    iconPath: "./folder/folder.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-open": {
    iconPath: "./folder/open.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-root": {
    iconPath: "./folder/root.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
  "folder-root-open": {
    iconPath: "./folder/root-open.svg",
    folderNames: [],
    folderNamesExpanded: [],
  },
};
